// Top-player Multikill reference — best-of-each-source pools run through
// ONE combine() pass (the same math a real save uses), gated PER CLASS for
// the formula's class talents. Use topMultikillFlatForClass(classKey).
// Large file: lazy-load it, don't import statically.
// Generated 2026-09-25T09:46:38.879Z · 84 players. Refresh: scripts/update-top-multikill.ts.

type FlatMap = Readonly<Record<string, number>>;

export const TOP_MULTIKILL_FLAT: FlatMap = {
    "Multikill": 127951,
    "Multikill / Active in AFK": 1,
    "Multikill / Active in AFK / Accuracy > 1.5 × Defence": 1,
    "Multikill / Active in AFK / Accuracy > 1.5 × Defence / Accuracy": 227520059831878750,
    "Multikill / Active in AFK / Accuracy > 1.5 × Defence / Target Defence": 50000,
    "Multikill / Active in AFK / Death Note built (TowerInfo[2] > 0.5)": 1,
    "Multikill / Active in AFK / Max damage ≥ HP × E": 1,
    "Multikill / Base Multikill": 2835.4707977207972,
    "Multikill / Base Multikill / Death Note building ×2": 102,
    "Multikill / Base Multikill / Death Note building ×2 / Building level (TowerInfo[2])": 51,
    "Multikill / Base Multikill / Just Passing By (Achievement 123) × 2": 2,
    "Multikill / Base Multikill / Monolithialism (Talent 654)": 576,
    "Multikill / Base Multikill / Monolithialism (Talent 654) / Active": 1,
    "Multikill / Base Multikill / Monolithialism (Talent 654) / Level": 150,
    "Multikill / Base Multikill / Monolithialism (Talent 654) / Max Level": 150,
    "Multikill / Base Multikill / Monolithialism (Talent 654) / Onyx Statues Owned": 32,
    "Multikill / Base Multikill / Monolithialism (Talent 654) / Talent Value": 18,
    "Multikill / Base Multikill / Multikill gear (Etc 29)": 111.95,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Hatrack Bonuses": 28.950000000000003,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Hatrack Bonuses / Nuget Cake Fedora": 28.950000000000003,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Hatrack Bonuses / Nuget Cake Fedora / Base": 15,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Hatrack Bonuses / Nuget Cake Fedora / Hatrack Bonus Multi": 1.9300000000000002,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Hatrack Bonuses / Nuget Cake Fedora / Hatrack Bonus Multi / Abalone Sashimi (Sushi Tier 37) — Hat Rack Multi (RoG Bonus 36)": 1,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Hatrack Bonuses / Nuget Cake Fedora / Hatrack Bonus Multi / Hatrack Boutique Bonus (Event Shop 30)": 10,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Hatrack Bonuses / Nuget Cake Fedora / Hatrack Bonus Multi / Hats Owned": 67,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Hatrack Bonuses / Nuget Cake Fedora / Hatrack Bonus Multi / Wild Boar (Companion 31)": 15,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses": 83,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal": 83,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolGoldKill × 6": 24,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolGoldKill × 6 / Slot 0": 4,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolGoldKill × 6 / Slot 11": 4,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolGoldKill × 6 / Slot 18": 4,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolGoldKill × 6 / Slot 20": 4,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolGoldKill × 6 / Slot 4": 4,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolGoldKill × 6 / Slot 9": 4,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolPinkKill": 11,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolPinkKill / Slot 10": 11,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolPlatinumKill × 2": 12,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolPlatinumKill × 2 / Slot 19": 6,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolPlatinumKill × 2 / Slot 2": 6,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolSilverKill × 12": 36,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolSilverKill × 12 / Slot 1": 3,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolSilverKill × 12 / Slot 12": 3,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolSilverKill × 12 / Slot 13": 3,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolSilverKill × 12 / Slot 14": 3,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolSilverKill × 12 / Slot 15": 3,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolSilverKill × 12 / Slot 16": 3,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolSilverKill × 12 / Slot 17": 3,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolSilverKill × 12 / Slot 3": 3,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolSilverKill × 12 / Slot 5": 3,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolSilverKill × 12 / Slot 6": 3,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolSilverKill × 12 / Slot 7": 3,
    "Multikill / Base Multikill / Multikill gear (Etc 29) / Obol Bonuses / Personal / ObolSilverKill × 12 / Slot 8": 3,
    "Multikill / Base Multikill / Salt Lick 8 (Multikill)": 30,
    "Multikill / Base Multikill / Salt Lick 8 (Multikill) / Level (SaltLick[8])": 10,
    "Multikill / Base Multikill / Stamps (Overkill)": 1856.5207977207976,
    "Multikill / Base Multikill / Stamps (Overkill) / b18": 1856.5207977207976,
    "Multikill / Base Multikill / Star signs (Multikill)": 150,
    "Multikill / Base Multikill / Star signs (Multikill) / Cullingo (Star Sign 47)": 15,
    "Multikill / Base Multikill / Star signs (Multikill) / Seraph Multi": 10,
    "Multikill / Base Multikill / Too Cute To Live (Achievement 148)": 1,
    "Multikill / Base Multikill / Wazzzzam! (Achievement 122) × 6": 6,
    "Multikill / Damage Tier": 51,
    "Multikill / Damage Tier / Exponent": 2,
    "Multikill / Damage Tier / Max Damage": 3.1730639460340186e+25,
    "Multikill / Damage Tier / Next tier at": 1.3510798882111488e+25,
    "Multikill / Damage Tier / Target HP": 3000000000,
    "Multikill / Damage Tier / Target HP / Prayer curses": 1,
    "Multikill / Damage Tier / Target HP / Prayer curses / Curse: Big Brain Time (Prayer 0)": 0,
    "Multikill / Damage Tier / Target HP / Prayer curses / Curse: Jawbreaker (Prayer 8)": 0,
    "Multikill / Damage Tier / Target HP / Prayer curses / Curse: Midas Minded (Prayer 7)": 0,
    "Multikill / Damage Tier / Target HP / Static HP": 3000000000,
    "Multikill / Damage Tier / Tier reached at": 6.755399441055744e+24,
    "Multikill / Multikill per Tier": 2453.2522851501444,
    "Multikill / Multikill per Tier / Balance Of Pain (Prayer 16)": 31,
    "Multikill / Multikill per Tier / Balance Of Pain (Prayer 16) / Base Bonus": 8,
    "Multikill / Multikill per Tier / Balance Of Pain (Prayer 16) / Level Scale": 3.9,
    "Multikill / Multikill per Tier / Balance Of Pain (Prayer 16) / Prayer Lv": 30,
    "Multikill / Multikill per Tier / Card Set 11 (Multikill per tier)": 42,
    "Multikill / Multikill per Tier / Card Set 11 (Multikill per tier) / Set 11": 42,
    "Multikill / Multikill per Tier / Cards (Card Type 80)": 606.375,
    "Multikill / Multikill per Tier / Cards (Card Type 80) / Boss6C Lv7": 490,
    "Multikill / Multikill per Tier / Cards (Card Type 80) / w4c1 Lv7": 18.375,
    "Multikill / Multikill per Tier / Cards (Card Type 80) / w5a1 Lv7": 24.5,
    "Multikill / Multikill per Tier / Cards (Card Type 80) / w6a5 Lv7": 73.5,
    "Multikill / Multikill per Tier / Death Note (W6 page)": 280,
    "Multikill / Multikill per Tier / Death Note (minibosses)": 80,
    "Multikill / Multikill per Tier / Lab chip (mkill)": 60,
    "Multikill / Multikill per Tier / MR_MASSACRE bubble (MKtierACTIVE)": 89.68608301360307,
    "Multikill / Multikill per Tier / MR_MASSACRE bubble (MKtierACTIVE) / Active (Sheepie or \"c15\" equipped)": 1,
    "Multikill / Multikill per Tier / MR_MASSACRE bubble (MKtierACTIVE) / Base": 89.68608301360307,
    "Multikill / Multikill per Tier / MR_MASSACRE bubble (MKtierACTIVE) / Level": 14285,
    "Multikill / Multikill per Tier / Mana Is Life (Talent 469)": 0,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58)": 308.9326765188834,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level": 409,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level": 396,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap": 396,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Base Level (N.js literal)": 100,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Checkout Takeout Achievement": 5,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Lv 1 Oxygen Atom": 10,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Lv 1 Oxygen Atom / Atom 7 Lv": 70,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Salt Lick 4": 20,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Salt Lick 4 / Per Lv": 2,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Salt Lick 4 / Salt Lick 4 Lv": 10,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Sovereign Fury Relic": 150,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Sovereign Fury Relic / Artifact 21 Base": 25,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Sovereign Fury Relic / Artifact 21 Tier": 6,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19": 75.621,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Higher Bonus Multi": 1.9500000000000002,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Higher Bonus Multi / Crystal Comb Pristine Charm": 1.3,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Higher Bonus Multi / Crystal Comb Pristine Charm / Pristine 8 Bonus": 30,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Higher Bonus Multi / Gem Shop Multi": 1.5,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Higher Bonus Multi / Gem Shop Multi / Gem Items 11": 5,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Summoning Battles": 14,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Summoning Battles / Cyan": 10.5,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Summoning Battles / Cyan / Battle 14": 10.5,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Summoning Battles / Teal": 3.5,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Summoning Battles / Teal / Battle 9": 3.5,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined)": 2.77,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Godshard Set": 15,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Regalis Achievement (379)": 1,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Sovereign Winz Lantern": 150,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Sovereign Winz Lantern / Artifact 32 Base": 25,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Sovereign Winz Lantern / Artifact 32 Tier": 6,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Spectre Stars Achievement (373)": 1,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / W6 Merit Shop (Task)": 10,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / Talent Book Library Base": 25,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / W3 Merit Shop Unlock": 10,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / W3 Merit Shop Unlock / Per Point": 2,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Max Book Lv Cap / W3 Merit Shop Unlock / W3 Merit Points Spent": 5,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Points Invested": 409,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Base Level / Reference Character: JourneyBear": 409,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Effective Level / Bonus Levels": 0,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Speedrun Highscore Maps": 115,
    "Multikill / Multikill per Tier / Master Of The System (Talent 58) / Talent Value": 13.431855500821017,
    "Multikill / Multikill per Tier / Measurement 9 (Multikill per tier)": 307.4176319321284,
    "Multikill / Multikill per Tier / Multikill Per Tier Arcade Bonus (Arcade 8)": 20.09950248756219,
    "Multikill / Multikill per Tier / Multikill Per Tier Arcade Bonus (Arcade 8) / Companion 27 Multi": 2,
    "Multikill / Multikill per Tier / Multikill Per Tier Arcade Bonus (Arcade 8) / Maxed Multi (101)": 2,
    "Multikill / Multikill per Tier / Multikill Per Tier Arcade Bonus (Arcade 8) / Raw (lv=101)": 5.024875621890548,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71)": 253.43878250231518,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Equipment Bonuses": 50,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Equipment Bonuses / Emperor Geta": 20,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Equipment Bonuses / Emperor Kabuto": 30,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses": 125.43878250231519,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Tome Elite Nametag": 68.42115409217192,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Tome Elite Nametag / Base": 12,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Tome Elite Nametag / Gallery Bonus Multi": 2.280705136405731,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Tome Elite Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49)": 50,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Tome Elite Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49) / Bonus": 50,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Tome Elite Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49) / Owned": 1,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Tome Elite Nametag / Gallery Bonus Multi / Codfrey Rulz OK (Bubble Y13, capped 20)": 17.447374390525994,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Tome Elite Nametag / Gallery Bonus Multi / Coralcave Crab (Card w7a11, capped 10)": 7,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Tome Elite Nametag / Gallery Bonus Multi / Dulce Vitiri (Sushi Tier 55) — Gallery Bonus Multi (RoG Bonus 54)": 1,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Tome Elite Nametag / Gallery Bonus Multi / Gallery Level": 30,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Tome Elite Nametag / Gallery Bonus Multi / Gallery Level / Level": 10,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Tome Elite Nametag / Gallery Bonus Multi / Glasstic Brain (Clam Work 7)": 3,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Tome Elite Nametag / Gallery Bonus Multi / Silkrode Motherboard (Chip 16)": 10,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Tome Elite Nametag / Gallery Bonus Multi / Skull Shop Tier 3 (Killroy 3)": 9.623139250047108,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Tome Elite Nametag / Level": 11,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Tome Elite Nametag / Tier": 2.5,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Vman Nametag": 57.017628410143274,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Vman Nametag / Base": 10,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Vman Nametag / Gallery Bonus Multi": 2.280705136405731,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Vman Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49)": 50,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Vman Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49) / Bonus": 50,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Vman Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49) / Owned": 1,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Vman Nametag / Gallery Bonus Multi / Codfrey Rulz OK (Bubble Y13, capped 20)": 17.447374390525994,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Vman Nametag / Gallery Bonus Multi / Coralcave Crab (Card w7a11, capped 10)": 7,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Vman Nametag / Gallery Bonus Multi / Dulce Vitiri (Sushi Tier 55) — Gallery Bonus Multi (RoG Bonus 54)": 1,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Vman Nametag / Gallery Bonus Multi / Gallery Level": 30,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Vman Nametag / Gallery Bonus Multi / Gallery Level / Level": 10,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Vman Nametag / Gallery Bonus Multi / Glasstic Brain (Clam Work 7)": 3,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Vman Nametag / Gallery Bonus Multi / Silkrode Motherboard (Chip 16)": 10,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Vman Nametag / Gallery Bonus Multi / Skull Shop Tier 3 (Killroy 3)": 9.623139250047108,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Vman Nametag / Level": 5,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Nametag Bonuses / Vman Nametag / Tier": 2.5,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses": 78,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal": 78,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyper3 × 12": 36,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyper3 × 12 / Slot 1": 3,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyper3 × 12 / Slot 12": 3,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyper3 × 12 / Slot 13": 3,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyper3 × 12 / Slot 14": 3,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyper3 × 12 / Slot 15": 3,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyper3 × 12 / Slot 16": 3,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyper3 × 12 / Slot 17": 3,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyper3 × 12 / Slot 3": 3,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyper3 × 12 / Slot 5": 3,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyper3 × 12 / Slot 6": 3,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyper3 × 12 / Slot 7": 3,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyper3 × 12 / Slot 8": 3,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyperB3 × 6": 42,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyperB3 × 6 / Slot 0": 7,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyperB3 × 6 / Slot 11": 7,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyperB3 × 6 / Slot 18": 7,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyperB3 × 6 / Slot 20": 7,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyperB3 × 6 / Slot 4": 7,
    "Multikill / Multikill per Tier / Multikill per tier gear (Etc 71) / Obol Bonuses / Personal / ObolHyperB3 × 6 / Slot 9": 7,
    "Multikill / Multikill per Tier / Post Office 13b": 9.782608695652174,
    "Multikill / Multikill per Tier / Post Office 13b / Utilitarian_Capsule slot1": 9.782608695652174,
    "Multikill / Multikill per Tier / Shiny Pets (Breeding 4)": 80,
    "Multikill / Multikill per Tier / Star signs (Multikill per tier)": 30,
    "Multikill / Multikill per Tier / Star signs (Multikill per tier) / Killian Maximus (Star Sign 78)": 3,
    "Multikill / Multikill per Tier / Star signs (Multikill per tier) / Seraph Multi": 10,
    "Multikill / Multikill per Tier / Trilobite Rock (Artifact 26)": 150,
    "Multikill / Multikill per Tier / Vials (Overkill)": 104.51999999999998,
    "Multikill / Multikill per Tier / Vials (Overkill) / SLOWERGY_DRINK": 104.51999999999998,
    "Multikill / Multikill per Tier / Void Radius (Talent 46)": 0,
  };

export const TOP_MULTIKILL_PROFILE_OVERRIDES: Readonly<Record<string, FlatMap>> = {
  "t46": {
  },
  "t469": {
    "Multikill": 129727,
    "Multikill / Multikill per Tier": 2488.0843264938135,
    "Multikill / Multikill per Tier / Mana Is Life (Talent 469)": 34.83204134366925,
  },
};

export const TOP_MULTIKILL_CLASS_PROFILE: Readonly<Record<string, string>> = {
  "Beginner": "base",
  "Journeyman": "base",
  "Maestro": "base",
  "Voidwalker": "t46",
  "Warrior": "base",
  "Barbarian": "base",
  "Blood_Berserker": "base",
  "Death_Bringer": "base",
  "Squire": "base",
  "Divine_Knight": "base",
  "Archer": "base",
  "Bowman": "base",
  "Siege_Breaker": "base",
  "Hunter": "base",
  "Beast_Master": "base",
  "Wind_Walker": "base",
  "Mage": "base",
  "Shaman": "base",
  "Bubonic_Conjuror": "base",
  "Arcane_Cultist": "base",
  "Wizard": "t469",
  "Elemental_Sorcerer": "t469",
  "Royal_Guardian": "base"
};

/** The top Multikill reference for a class — base merged with its profile. */
export function topMultikillFlatForClass(classKey: string | null | undefined): FlatMap {
  const profile = classKey ? TOP_MULTIKILL_CLASS_PROFILE[classKey] : undefined;
  const override = profile ? TOP_MULTIKILL_PROFILE_OVERRIDES[profile] : undefined;
  return override ? { ...TOP_MULTIKILL_FLAT, ...override } : TOP_MULTIKILL_FLAT;
}
