// ============================================================================
// gen-dr-items.ts — extract every equipment item that grants a Drop-Rate
// stat (from website-data.json), distilling them into a compact catalog the
// equipment resolver can iterate to surface "unequipped but capable" items
// in the DeepView. Output:
//
//   web/lib/corgan/stats/data/dr-items.gen.ts
//
// Each entry carries the item's built-in DR-style stat + numeric value
// (matching exactly what equipment.ts's `itemUqMatch` looks up at runtime),
// the equipment Type, and a humanised display name.
//
// Run: npx tsx web/scripts/gen-dr-items.ts
// ============================================================================

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

type Json = any;

const DATA_PATH = resolve(
  __dirname,
  "..",
  "lib",
  "it",
  "data",
  "website-data.json"
);
const OUTPUT_PATH = resolve(
  __dirname,
  "..",
  "lib",
  "corgan",
  "stats",
  "data",
  "dr-items.gen.ts"
);

const data: Json = JSON.parse(readFileSync(DATA_PATH, "utf8"));

// These are the stat-name strings the equipment resolver treats as "etcBonus
// 2 / 102 / 99 / 91" (Drop Rate, Drop Chance, Bonus Drop Rate, Drop Rate
// Multi). Mirrors custommaps.IDforETCbonus on the descriptor side.
const DR_STATS = new Set([
  "%_DROP_RATE",
  "%_DROP_CHANCE",
  "%_BONUS_DROP_RATE",
  "%_DROP_RATE_MULTI",
]);

// Skip replica trophy/nametag mirrors — those are the same items
// reachable via the same equip slot, and including both makes the catalog
// double-counted from the user's perspective.
const SKIP_TYPES = new Set(["REPLICA_TROPHY", "REPLICA_NAMETAG"]);

function humanize(raw: string): string {
  return raw.replace(/_/g, " ");
}

type CatalogEntry = {
  key: string; // EquipmentHats52 — matches `equipOrder` slot values
  name: string;
  type: string;
  stat: string; // %_DROP_RATE / %_DROP_RATE_MULTI / …
  uq: 1 | 2;
  val: number;
};

const catalog: CatalogEntry[] = [];

for (const [key, item] of Object.entries(data.items)) {
  const v = item as Json;
  const type = v.Type;
  if (!type || SKIP_TYPES.has(type)) continue;

  let match: { stat: string; uq: 1 | 2; val: number } | null = null;
  if (DR_STATS.has(v.UQ1txt)) {
    match = { stat: v.UQ1txt, uq: 1, val: Number(v.UQ1val) || 0 };
  } else if (DR_STATS.has(v.UQ2txt)) {
    match = { stat: v.UQ2txt, uq: 2, val: Number(v.UQ2val) || 0 };
  }
  if (!match) continue;

  catalog.push({
    key,
    name: humanize(v.displayName || key),
    type,
    stat: match.stat,
    uq: match.uq,
    val: match.val,
  });
}

// Sort: by stat (DR first, then DR_CHANCE, BONUS_DR, DR_MULTI), then by
// equipment type, then by val desc within the group. Mostly for the .gen.ts
// file's readability — runtime iteration order doesn't matter.
const STAT_ORDER = [
  "%_DROP_RATE",
  "%_DROP_CHANCE",
  "%_BONUS_DROP_RATE",
  "%_DROP_RATE_MULTI",
];
catalog.sort((a, b) => {
  const si = STAT_ORDER.indexOf(a.stat) - STAT_ORDER.indexOf(b.stat);
  if (si !== 0) return si;
  if (a.type !== b.type) return a.type.localeCompare(b.type);
  return b.val - a.val;
});

const lines: string[] = [];
lines.push(
  "// AUTO-GENERATED by web/scripts/gen-dr-items.ts — do not edit by hand."
);
lines.push("// Source: web/lib/it/data/website-data.json");
lines.push("// Regenerate: npx tsx web/scripts/gen-dr-items.ts");
lines.push("");
lines.push("export type DrItem = {");
lines.push("  /** Raw key in items{} — matches equipOrder slot values. */");
lines.push("  key: string;");
lines.push('  /** Display name, e.g. "Efaunt Helmet". */');
lines.push("  name: string;");
lines.push("  /** Equipment type bucket (HELMET, SHIRT, ATTIRE, TROPHY, …). */");
lines.push("  type: string;");
lines.push("  /** Which DR-family stat the built-in bonus carries. */");
lines.push("  stat:");
lines.push('    | "%_DROP_RATE"');
lines.push('    | "%_DROP_CHANCE"');
lines.push('    | "%_BONUS_DROP_RATE"');
lines.push('    | "%_DROP_RATE_MULTI";');
lines.push("  /** UQ slot the stat lives in (1 = main, 2 = secondary). */");
lines.push("  uq: 1 | 2;");
lines.push("  /** Base value of the built-in stat. Multipliers (Grid 172,");
lines.push("   *  chip doubling) are applied at runtime in equipment.ts. */");
lines.push("  val: number;");
lines.push("};");
lines.push("");
lines.push("export const DR_ITEMS: DrItem[] = [");
for (const e of catalog) {
  lines.push(
    `  { key: ${JSON.stringify(e.key)}, name: ${JSON.stringify(e.name)}, type: ${JSON.stringify(e.type)}, stat: ${JSON.stringify(e.stat)}, uq: ${e.uq}, val: ${e.val} },`
  );
}
lines.push("];");
lines.push("");

writeFileSync(OUTPUT_PATH, lines.join("\n"));
console.log(`Wrote ${OUTPUT_PATH}`);
console.log(`Items: ${catalog.length}`);
const byType = catalog.reduce((m: Record<string, number>, e) => {
  m[e.type] = (m[e.type] || 0) + 1;
  return m;
}, {});
console.log(`By type:`);
for (const [t, n] of Object.entries(byType).sort((a, b) => b[1] - a[1])) {
  console.log(`  ${t.padEnd(20)} ${n}`);
}
