// Auto-extracted from web/lib/it/data/website-data.json.mapNames
// Regenerate with: python -c "import json; d=json.load(open('web/lib/it/data/website-data.json')); ..."
// Indexed by map index - same numbering as save.data.CurrentMap_N and data.MapBon[i].

export const MAP_NAMES: readonly string[] = [
  "Blunder_Hills", "Spore_Meadows", "Froggy_Fields", "JungleZ", "PlayerSelect", "PlayerSelect", "Tunnels_Entrance", "Freefall_Caverns",
  "Poopy_Sewers", "The_Office", "The_Ol'_Straightaway", "Echoing_Egress", "Slip_Slidy_Ledges", "The_Base_Of_The_Bark", "Valley_Of_The_Beans", "Rats_Nest",
  "Jungle_Perimeter", "Birch_Enclave", "Hollowed_Trunk", "Winding_Willows", "TutorialA", "TutorialB", "TutorialC", "TutorialD",
  "Vegetable_Patch", "JungleX", "Forest_Outskirts", "Encroaching_Forest_Villas", "Tucked_Away", "End_Of_The_Road", "The_Roots", "Where_the_Branches_End",
  "Motherlode_Pit", "How_Did_u_get_here", "Miningg1", "Miningg2", "Dewdrop_Colosseum", "Spike_Surprise", "Meel's_Crypt", "Grandfrog's_Backyard",
  "Grandfrog's_Gazebo", "Pet_Park", "Grand_Owl_Perch", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "YumYum_Grotto", "Jar_Bridge", "The_Mimic_Hole", "Dessert_Dunes", "Salty_Shores", "Faraway_Piers",
  "Filler", "The_Grandioso_Canyon", "Shifty_Sandbox", "Pincer_Plateau", "Slamabam_Straightaway", "Deepwater_Docks", "The_Ring", "Up_Up_Down_Down",
  "Sands_of_Time", "Djonnuttown", "Efaunt's_Tomb", "Bandit_Bob's_Hideout", "Sandstone_Colosseum", "Mummy_Memorial", "Heaty_Hole", "Gravel_Tomb",
  "YumYum_Islands", "The_Oasis", "Z", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Z", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Z", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Z", "Z", "Frostbite_Towndra", "Steep_Sheep_Ledge", "Trappers_Folley", "Snowfield_Outskirts",
  "The_Stache_Split", "Refrigeration_Station", "Mamooooth_Mountain", "Rollin'_Tundra", "Signature_Slopes", "Thermonuclear_Climb", "Waterlogged_Entrance", "Cryo_Catacombs",
  "Overpass_of_Sound", "Crystal_Basecamp", "Chizoar's_Cavern", "Coldsnap_Colosseum", "Wam_Wonderland", "Hell_Hath_Frozen_Over", "Inside_the_Igloo", "Igloo's_Basement",
  "Equinox_Valley", "Z", "Z", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Z", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Z", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Z", "Z", "Z", "Z", "Outer_World_Town", "Spaceway_Raceway",
  "TV_Outpost", "Donut_Drive-In", "Outskirts_of_Fallstar_Isle", "Mountainous_Deugh", "Wurm_Highway", "Jelly_Cube_Bridge", "Cocoa_Tunnel", "Standstill_Plains",
  "Shelled_Shores", "The_Untraveled_Octopath", "Flamboyant_Bayou", "Enclave_of_Eyes", "Astro_Colosseum", "Enclave_a_la_Troll", "The_Rift", "Z",
  "Z", "Z", "Z", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Z", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Z", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Z", "Z", "Z", "Z", "Z", "Z",
  "Magma_Rivertown", "Naut_Sake_Perimeter", "Niagrilled_Falls", "The_Killer_Roundabout", "Cracker_Jack_Lake", "The_Great_Molehill", "Erruption_River", "Mount_Doomish",
  "OJ_Bay", "Lampar_Lake", "Spitfire_River", "Miner_Mole_Outskirts", "Crawly_Catacombs", "The_Worm_Nest", "KattleKruk's_Volcano", "Molten_Colosseum",
  "The_Hole", "Z", "Z", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Z", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Z", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Z", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Spirit_Village", "Gooble_Goop_Creek", "Picnic_Bridgeways", "Irrigation_Station", "Troll_Playground", "Edge_of_the_Valley",
  "Bamboo_Laboredge", "Lightway_Path", "Troll_Broodnest", "Above_the_Clouds", "Sleepy_Skyline", "Dozey_Dogpark", "Yolkrock_Basin", "Chieftain_Stairway",
  "Emperor's_Castle_Doorstep", "Whimsical_Colosseum", "Emperor's_Castle", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Z", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Z", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Z", "Z", "Z", "Z", "Z", "Z",
  "Z", "Z", "Z", "Z", "Shimmerfin_Grove", "Refraction_Bend", "Doodle_Reef", "Seaweed_Street",
  "Barnacle_Curb", "Balloon_Bay", "The_Clamworks", "Plastic_Basin", "Puffpuff_Overpass", "Pinpoint_Summit", "Middle_of_Nowhere", "Coralcave_Outskirts",
  "Coralcave_Perimeter", "Unused", "Unused", "Deep_End_of_the_Koipond", "Minefield", "Pirate_Upper_Deck", "Sushi_Perimeter", "Jellofish_Fields",
  "Where_the_Kelp_Meets_Trench", "Trench_Precipice", "fillername", "fillername", "fillername", "Pirate_Mess_Hall", "Dreadnaught_Chamber",
] as const;
