// ===== Idleon updater — game-data emitters =====
// Regenerates the committed data files the corgan engine reads
// (web/lib/corgan/stats/data/game/{items,customlists}.js) from the live N.js.
//
// Strategy: MERGE onto the committed file, never regenerate blind —
//   - items.js: update existing keys with live values, append genuinely new
//     items, never drop a committed key.
//   - customlists.js: emit ONLY the names the committed file already exports,
//     in committed order (this filters out the lib-noise getters our generic
//     extractor also picks up, e.g. get_version/test/next).
// This keeps the contract stable and the git diff limited to real changes.

import type { Item } from "./extract";

function header(what: string): string {
  return `// Auto-generated by web/scripts/updater -- do not edit\n// Source: live N.js — ${what}\n\n`;
}

export type ItemsResult = { text: string; updated: number; added: number; kept: number };

/** Merge extracted items onto the committed ITEMS map. */
export function buildItemsFile(
  extracted: Record<string, Item>,
  committed: Record<string, Item>,
): ItemsResult {
  const merged: Record<string, Item> = {};
  let updated = 0;
  let kept = 0;
  for (const k of Object.keys(committed)) {
    if (k in extracted) {
      merged[k] = extracted[k];
      if (JSON.stringify(extracted[k]) !== JSON.stringify(committed[k])) updated++;
    } else {
      merged[k] = committed[k]; // never drop a committed item
      kept++;
    }
  }
  let added = 0;
  for (const k of Object.keys(extracted)) {
    if (!(k in merged)) {
      merged[k] = extracted[k];
      added++;
    }
  }
  const text = header("ItemDefinitions (equip/consumable/item/quest)") +
    `export var ITEMS = ${JSON.stringify(merged, null, 2)};\n`;
  return { text, updated, added, kept };
}

export type ListsResult = { text: string; updated: number; missing: string[] };

/** Emit the committed list names, in committed order, with live values. */
export function buildListsFile(
  extracted: Record<string, unknown>,
  committedText: string,
  committedValues: Record<string, unknown>,
): ListsResult {
  const names = [...committedText.matchAll(/^export var ([A-Za-z0-9_]+)/gm)].map((m) => m[1]);
  const missing: string[] = [];
  let updated = 0;
  const lines = names.map((name) => {
    let val: unknown;
    if (name in extracted) {
      val = extracted[name];
      if (JSON.stringify(val) !== JSON.stringify(committedValues[name])) updated++;
    } else {
      val = committedValues[name]; // couldn't extract this build — keep old
      missing.push(name);
    }
    return `export var ${name} = ${JSON.stringify(val)};`;
  });
  const text = header("CustomLists + CustomLists2 + CustomLists3") + lines.join("\n\n") + "\n";
  return { text, updated, missing };
}
