// ===== MAIN-THREAD SAVE DATA =====
// 1:1 port of corgan-source/js/save/data.js. These globals are populated
// during save load and read by every system on the main thread.

export let labData: any[] = [];
export let dreamData: any[] = [];
export let divinityData: any[] = [];
export let optionsListData: any[] = [];
export let tasksW7Data: any[] = [];
export let numCharacters = 10;
export let charClassData: any[] = [];
export let skillLvData: any[] = [];
export let skillLvMaxData: any[] = [];
export let playerStuffData: any[] = [];
export let cauldronInfoData: any[] = [];
export let cauldronBubblesData: any[] = [];
export let klaData: any[] = [];
export let equipOrderData: any[] = [];
export let equipQtyData: any[] = [];
export let stampLvData: Record<string, any> = {};
export let starSignData: any[] = [];
export let emmData: any[] = [];
export let prayersPerCharData: any[] = [];
export let postOfficeData: any[] = [];
export let cardEquipData: any[] = [];
export let csetEqData: any[] = [];
export let currentMapData: any[] = [];
export let mapBonData: any[] = [];
export let obolNamesData: any[] = [];
export let obolMapsData: any[] = [];
export let obolFamilyNames: any[] = [];
export let obolFamilyMaps: Record<string, any> = {};
export let buffsActiveData: any[] = [];
export let loadedSaveFormat = "";
export let saveGlobalTime = 0;
export let tournamentDay = 0;
export let cachedAFKRate: any = null;

export type DataUpdate = {
  labData?: any[];
  dreamData?: any[];
  divinityData?: any[];
  optionsListData?: any[];
  tasksW7Data?: any[];
  numCharacters?: number;
  charClassData?: any[];
  skillLvData?: any[];
  skillLvMaxData?: any[];
  playerStuffData?: any[];
  cauldronInfoData?: any[];
  cauldronBubblesData?: any[];
  klaData?: any[];
  equipOrderData?: any[];
  equipQtyData?: any[];
  stampLvData?: Record<string, any>;
  starSignData?: any[];
  emmData?: any[];
  prayersPerCharData?: any[];
  postOfficeData?: any[];
  cardEquipData?: any[];
  csetEqData?: any[];
  currentMapData?: any[];
  mapBonData?: any[];
  obolNamesData?: any[];
  obolMapsData?: any[];
  obolFamilyNames?: any[];
  obolFamilyMaps?: Record<string, any>;
  buffsActiveData?: any[];
  loadedSaveFormat?: string;
  saveGlobalTime?: number;
  tournamentDay?: number;
  cachedAFKRate?: any;
};

export function assignSaveData(u: DataUpdate): void {
  if ("labData" in u) labData = u.labData!;
  if ("dreamData" in u) dreamData = u.dreamData!;
  if ("divinityData" in u) divinityData = u.divinityData!;
  if ("optionsListData" in u) optionsListData = u.optionsListData!;
  if ("tasksW7Data" in u) tasksW7Data = u.tasksW7Data!;
  if ("numCharacters" in u) numCharacters = u.numCharacters!;
  if ("charClassData" in u) charClassData = u.charClassData!;
  if ("skillLvData" in u) skillLvData = u.skillLvData!;
  if ("skillLvMaxData" in u) skillLvMaxData = u.skillLvMaxData!;
  if ("playerStuffData" in u) playerStuffData = u.playerStuffData!;
  if ("cauldronInfoData" in u) cauldronInfoData = u.cauldronInfoData!;
  if ("cauldronBubblesData" in u) cauldronBubblesData = u.cauldronBubblesData!;
  if ("klaData" in u) klaData = u.klaData!;
  if ("equipOrderData" in u) equipOrderData = u.equipOrderData!;
  if ("equipQtyData" in u) equipQtyData = u.equipQtyData!;
  if ("stampLvData" in u) stampLvData = u.stampLvData!;
  if ("starSignData" in u) starSignData = u.starSignData!;
  if ("emmData" in u) emmData = u.emmData!;
  if ("prayersPerCharData" in u) prayersPerCharData = u.prayersPerCharData!;
  if ("postOfficeData" in u) postOfficeData = u.postOfficeData!;
  if ("cardEquipData" in u) cardEquipData = u.cardEquipData!;
  if ("csetEqData" in u) csetEqData = u.csetEqData!;
  if ("currentMapData" in u) currentMapData = u.currentMapData!;
  if ("mapBonData" in u) mapBonData = u.mapBonData!;
  if ("obolNamesData" in u) obolNamesData = u.obolNamesData!;
  if ("obolMapsData" in u) obolMapsData = u.obolMapsData!;
  if ("obolFamilyNames" in u) obolFamilyNames = u.obolFamilyNames!;
  if ("obolFamilyMaps" in u) obolFamilyMaps = u.obolFamilyMaps!;
  if ("buffsActiveData" in u) buffsActiveData = u.buffsActiveData!;
  if ("loadedSaveFormat" in u) loadedSaveFormat = u.loadedSaveFormat!;
  if ("saveGlobalTime" in u) saveGlobalTime = u.saveGlobalTime!;
  if ("tournamentDay" in u) tournamentDay = u.tournamentDay!;
  if ("cachedAFKRate" in u) cachedAFKRate = u.cachedAFKRate;
}
