// AUTO-GENERATED by registry/gen-registry.ts — DO NOT EDIT.
// Maps each N.js formula / mirrored-constant (@njs annotations) to the ported file(s).
export const FORMULA_REGISTRY: Record<string, string[]> = {
  "ArmoryUpgBonus": [
    "lib/arkh/stats/data/w7/royalG.ts"
  ],
  "ClassFamilyBonuses[16]": [
    "lib/arkh/stats/systems/common/familyBonus.ts"
  ],
  "FriendBonusQTY": [
    "lib/arkh/stats/systems/common/friend.ts"
  ],
  "FriendBonusSlots": [
    "lib/arkh/stats/systems/common/friend.ts"
  ],
  "FriendBonusXtraMulti": [
    "lib/arkh/stats/systems/common/friend.ts"
  ],
  "HatrackBonusMulti": [
    "lib/arkh/stats/systems/w7/gallery.ts"
  ],
  "PodiumsOwned_Lv4": [
    "lib/arkh/stats/systems/w7/gallery.ts"
  ],
  "PtsLeftCook_P": [
    "lib/arkh/stats/systems/common/cookingMastery.ts"
  ],
  "RandoListo2[8]": [
    "lib/arkh/stats/systems/common/cookingMastery.ts"
  ],
  "RoG_BonusQTY": [
    "lib/arkh/stats/data/w7/jelly.ts"
  ],
  "StatueBon": [
    "lib/arkh/stats/data/w7/royalG.ts"
  ],
  "TotalStatz": [
    "lib/arkh/stats/data/w7/royalG.ts"
  ],
  "WinBonus": [
    "lib/arkh/stats/systems/w6/summoning.ts"
  ]
};
