// AUTO-GENERATED by registry/gen-registry.ts — DO NOT EDIT.
// Maps each N.js formula / mirrored-constant (@njs annotations) to the ported file(s).
export const FORMULA_REGISTRY: Record<string, string[]> = {
  "ArcaneMapMulti_bon": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "ArmoryUpgBonus": [
    "lib/arkh/stats/data/w7/royalG.ts"
  ],
  "BigFishBonuses": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "Bonus_Minor": [
    "lib/arkh/stats/systems/coin/divinityMinor.ts"
  ],
  "CardsCollected": [
    "lib/arkh/stats/systems/coin/accountKills.ts"
  ],
  "ClassFamilyBonuses[16]": [
    "lib/arkh/stats/systems/common/familyBonus.ts"
  ],
  "CloudBonus": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "CoralKidUpgBonus": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "CropSCbonMulti": [
    "lib/arkh/stats/systems/w6/farming.ts"
  ],
  "DeathNoteRank": [
    "lib/arkh/stats/systems/coin/gambit.ts"
  ],
  "DivMinorBonus": [
    "lib/arkh/stats/systems/coin/divinityMinor.ts"
  ],
  "Fountain_BonTOT": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "FriendBonusQTY": [
    "lib/arkh/stats/systems/common/friend.ts"
  ],
  "FriendBonusSlots": [
    "lib/arkh/stats/systems/common/friend.ts"
  ],
  "FriendBonusXtraMulti": [
    "lib/arkh/stats/systems/common/friend.ts"
  ],
  "GambitBonuses": [
    "lib/arkh/stats/systems/coin/gambit.ts"
  ],
  "GambitPTSmulti": [
    "lib/arkh/stats/systems/coin/gambit.ts"
  ],
  "GambitPts": [
    "lib/arkh/stats/systems/coin/gambit.ts"
  ],
  "GambitPtsREQ": [
    "lib/arkh/stats/systems/coin/gambit.ts"
  ],
  "Grid_Bonus": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "HatrackBonusMulti": [
    "lib/arkh/stats/systems/w7/gallery.ts"
  ],
  "MeritocBonusz": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "MonsterCash": [
    "lib/arkh/stats/systems/coin/coin.ts"
  ],
  "OverkillQTY": [
    "lib/arkh/stats/systems/coin/gambit.ts"
  ],
  "OverkillStuffs": [
    "lib/arkh/stats/systems/coin/coin.ts"
  ],
  "PocketDivOwned": [
    "lib/arkh/stats/systems/coin/divinityMinor.ts"
  ],
  "PodiumsOwned_Lv4": [
    "lib/arkh/stats/systems/w7/gallery.ts"
  ],
  "PtsLeftCook_P": [
    "lib/arkh/stats/systems/common/cookingMastery.ts"
  ],
  "RandoListo2[8]": [
    "lib/arkh/stats/systems/common/cookingMastery.ts"
  ],
  "RoG_BonusQTY": [
    "lib/arkh/stats/data/w7/jelly.ts",
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "StatueBon": [
    "lib/arkh/stats/data/w7/royalG.ts",
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "SuperBitType": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "TotalStatz": [
    "lib/arkh/stats/data/w7/royalG.ts"
  ],
  "TotalTitanKills": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "VaultKillzTotal": [
    "lib/arkh/stats/systems/coin/accountKills.ts"
  ],
  "WinBonus": [
    "lib/arkh/stats/systems/w6/summoning.ts"
  ],
  "ZenithMarketBonus": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ]
};
