// AUTO-GENERATED by registry/gen-registry.ts — DO NOT EDIT.
// Maps each N.js formula / mirrored-constant (@njs annotations) to the ported file(s).
export const FORMULA_REGISTRY: Record<string, string[]> = {
  "AllShimmerBonuses": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "ArcaneMapMulti_bon": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "ArmoryUpgBonus": [
    "lib/arkh/stats/data/w7/royalG.ts"
  ],
  "B_UPG": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "BigFishBonuses": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "Bonus_MAJOR": [
    "lib/arkh/stats/systems/w5/divinity.ts"
  ],
  "Bonus_Minor": [
    "lib/arkh/stats/systems/coin/divinityMinor.ts",
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "Button_Bonuses": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "CardLv": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "CardsCollected": [
    "lib/arkh/stats/systems/coin/accountKills.ts"
  ],
  "ClassFamilyBonuses[16]": [
    "lib/arkh/stats/systems/common/familyBonus.ts"
  ],
  "CloudBonus": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "CompassBonus": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "CoralKidUpgBonus": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "CropSCbonMulti": [
    "lib/arkh/stats/systems/w6/farming.ts"
  ],
  "DancingCoralBonus": [
    "lib/arkh/stats/systems/exp/dancingCoral.ts",
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "DeathNoteRank": [
    "lib/arkh/stats/systems/coin/gambit.ts"
  ],
  "DivMinorBonus": [
    "lib/arkh/stats/systems/coin/divinityMinor.ts"
  ],
  "ExoticBonusQTY": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "Fountain_BonTOT": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "FriendBonusQTY": [
    "lib/arkh/stats/systems/common/friend.ts"
  ],
  "FriendBonusSlots": [
    "lib/arkh/stats/systems/common/friend.ts"
  ],
  "FriendBonusStatz": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "FriendBonusXtraMulti": [
    "lib/arkh/stats/systems/common/friend.ts"
  ],
  "GambitBonuses": [
    "lib/arkh/stats/systems/coin/gambit.ts"
  ],
  "GambitPTSmulti": [
    "lib/arkh/stats/systems/coin/gambit.ts"
  ],
  "GambitPts": [
    "lib/arkh/stats/systems/coin/gambit.ts"
  ],
  "GambitPtsREQ": [
    "lib/arkh/stats/systems/coin/gambit.ts"
  ],
  "Grid_Bonus": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "GrimoireUpgBonus": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "HatrackBonusMulti": [
    "lib/arkh/stats/systems/w7/gallery.ts"
  ],
  "MSA_Bonus": [
    "lib/arkh/stats/systems/exp/exp.ts",
    "lib/arkh/stats/systems/exp/msa.ts"
  ],
  "MeritocBonusz": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "MonsterCash": [
    "lib/arkh/stats/systems/coin/coin.ts"
  ],
  "MonumentROGbonuses": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "OverkillQTY": [
    "lib/arkh/stats/systems/coin/gambit.ts"
  ],
  "OverkillStuffs": [
    "lib/arkh/stats/systems/coin/coin.ts"
  ],
  "PocketDivOwned": [
    "lib/arkh/stats/systems/coin/divinityMinor.ts"
  ],
  "PodiumsOwned_Lv4": [
    "lib/arkh/stats/systems/w7/gallery.ts"
  ],
  "PtsLeftCook_P": [
    "lib/arkh/stats/systems/common/cookingMastery.ts"
  ],
  "RandoListo2[8]": [
    "lib/arkh/stats/systems/common/cookingMastery.ts"
  ],
  "RecalcChipBonuses": [
    "lib/arkh/stats/systems/w4/lab.ts"
  ],
  "RoG_BonusQTY": [
    "lib/arkh/stats/data/w7/jelly.ts",
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "RooBonuses": [
    "lib/arkh/stats/systems/coin/coin.ts"
  ],
  "ShinyBonusS": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "StatueBon": [
    "lib/arkh/stats/data/w7/royalG.ts",
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "StickerBonus": [
    "lib/arkh/stats/systems/exp/exp.ts",
    "lib/arkh/stats/systems/exp/sticker.ts"
  ],
  "SuperBitType": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "TotalStatz": [
    "lib/arkh/stats/data/w7/royalG.ts"
  ],
  "TotalTitanKills": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "VaultKillzTotal": [
    "lib/arkh/stats/systems/coin/accountKills.ts"
  ],
  "VaultUpgBonus": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "WinBonus": [
    "lib/arkh/stats/systems/exp/exp.ts",
    "lib/arkh/stats/systems/w6/summoning.ts"
  ],
  "ZenithMarketBonus": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "_customBlock_AFKgainrates": [
    "lib/arkh/stats/systems/afk/afk.ts"
  ],
  "_customBlock_Companions": [
    "lib/arkh/stats/data/common/companions.ts"
  ],
  "_customBlock_ExpMulti": [
    "lib/arkh/stats/systems/exp/exp.ts"
  ],
  "_customBlock_FlurboShop": [
    "lib/arkh/stats/systems/coin/coin.ts"
  ],
  "_customBlock_GetSetBonus": [
    "lib/arkh/stats/systems/w3/setBonus.ts"
  ],
  "_customBlock_Holes2": [
    "lib/arkh/stats/systems/afk/afk.ts"
  ],
  "_customBlock_JellyOperation": [
    "lib/arkh/stats/data/w7/jelly.ts"
  ],
  "_customBlock_StarSigns": [
    "lib/arkh/stats/systems/common/starSign.ts"
  ],
  "_customBlock_chipBonuses": [
    "lib/arkh/stats/systems/w4/lab.ts"
  ],
  "_customBlock_prayersReal": [
    "lib/arkh/stats/systems/w3/prayer.ts"
  ]
};
