// web/scripts/updater/registry/gen-registry.ts
// Builds the formula registry by scanning `// @njs <name>` annotations across
// the ported engines. The registry maps each N.js formula/mirrored-constant
// name to the file(s) that port it. Regex scan (not AST) — simple and enough
// for "which file(s) to review". Run via gen() to (re)write the .gen.ts.
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
export const WEB_ROOT = join(__dirname, "../../..");
const ROOTS = ["lib/arkh", "lib/tome", "lib/cookingMastery", "lib/talentsLevel", "lib/dropRate"];
const ANNOT = /\/\/\s*@njs\s+([A-Za-z][A-Za-z0-9_]*(?:\[[0-9]+\])?)/g;

function walk(dir: string, acc: string[]): string[] {
  let entries: string[] = [];
  try { entries = readdirSync(dir); } catch { return acc; }
  for (const e of entries) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) walk(p, acc);
    else if (e.endsWith(".ts")) acc.push(p);
  }
  return acc;
}

export function buildRegistry(webRoot: string = WEB_ROOT): Record<string, string[]> {
  const map: Record<string, string[]> = {};
  for (const root of ROOTS) {
    for (const file of walk(join(webRoot, root), [])) {
      const txt = readFileSync(file, "utf8");
      let m: RegExpExecArray | null;
      ANNOT.lastIndex = 0;
      while ((m = ANNOT.exec(txt))) {
        const rel = relative(webRoot, file).replace(/\\/g, "/");
        (map[m[1]] ??= []).push(rel);
      }
    }
  }
  for (const k of Object.keys(map)) map[k] = [...new Set(map[k])].sort();
  return map;
}

export function renderRegistry(map: Record<string, string[]>): string {
  const sorted: Record<string, string[]> = {};
  for (const k of Object.keys(map).sort()) sorted[k] = map[k];
  return (
    "// AUTO-GENERATED by registry/gen-registry.ts — DO NOT EDIT.\n" +
    "// Maps each N.js formula / mirrored-constant (@njs annotations) to the ported file(s).\n" +
    "export const FORMULA_REGISTRY: Record<string, string[]> = " +
    JSON.stringify(sorted, null, 2) +
    ";\n"
  );
}

function gen(): void {
  const out = join(__dirname, "formula-registry.gen.ts");
  writeFileSync(out, renderRegistry(buildRegistry()), "utf8");
  console.log(`[registry] wrote ${out} (${Object.keys(buildRegistry()).length} entries)`);
}

if (import.meta.url === pathToFileURL(process.argv[1] || "").href) gen();
