// Per-task default classification, editable by hand. This file overrides the
// classification field inside topPlayers.ts (which is generated from the
// Google Sheet snapshot). Edit numbers here freely — they ship to production
// and become the default chip for every visitor (the user can still pick a
// different value in the UI, stored per-device in localStorage).
//
// Legend:
//   1  → Priority         (red)
//   3  → Doable           (green)
//   4  → Time Gated       (amber)
//   5  → Lucky Gated      (purple)
//   9  → Event/Update Gated (orange)
//   null → no default (leave the chip blank so the user decides)
//
// Do NOT use 12 (Capped) here — Capped is auto-applied by the UI when the
// player's pts hit the theoretical curve max.

export const DEFAULT_CLASSIFICATIONS: Readonly<Record<string, number | null>> = {
  "Account LV": 3,
  "Account Skills LV": 3,
  "Total Talent Max LV": 3,
  "Items Found": null,
  "Total Bubble LV": null,
  "Stamp Total LV": 4,
  "Cards Total LV": null,
  "Statue Total LV": 3,
  "Total Achievements Completed": null,
  "Unique Quests Completed": 9,
  "Total Tasks Completed": 9,
  "Vault Upgrade bonus LV": 1,
  "Most Money held in Storage": 3,
  "Most Spore Caps held in Inventory at once": 3,
  "Total Colosseum Score": 9,
  "Trophies Found": null,
  "Nametags Found": null,
  "Premium Hats Found": 9,
  "Best Spiketrap Surprise round": null,
  "Tournaments Registrations": 4,
  "Lava Dev Streams watched": 9,
  "Total Minigame Highscore": null,
  "Total AFK Hours claimed": 4,
  "DPS Record on Shimmer Island": 3,
  "Total Arcade Gold Ball Shop Upgrade LV": 9,
  "Most Balls earned from LBoFaF": 5,
  "Jackpots Hit in Arcade": 5,
  "Star Talent Points Owned": 3,
  "Average kills for a Crystal Spawn": 3,
  "Dungeon Rank": 9,
  "Highest Drop Rate Multi": null,
  "Constellations Completed": null,
  "Unique Obols Found": 9,
  "Total Vial LV": null,
  "Total Sigil LV": 4,
  "Post Office PO Boxes Earned": 3,
  "Highest Killroy Score on a Warrior": 4,
  "Highest Killroy Score on an Archer": 4,
  "Highest Killroy Score on a Mage": 4,
  "Megafeathers Earned from Orion": 4,
  "Megafish Earned from Poppy": 4,
  "Megaflesh Earned from Bubba": 4,
  "Fastest Time to kill Chaotic Efaunt (in Seconds)": 3,
  "Largest Oak Log Printer Sample": 3,
  "Largest Copper Ore Printer Sample": 3,
  "Largest Spore Cap Printer Sample": 3,
  "Largest Goldfish Printer Sample": 3,
  "Largest Fly Printer Sample": 3,
  "Total Best Wave in Worship": 3,
  "Best Non Duplicate Goblin Gorefest Wave": 3,
  "Total Prayer Upgrade LV": null,
  "Total Digits of all Deathnote Kills": 3,
  "Most Giants Killed in a Single Week": 3,
  "Total Refinery Rank": 4,
  "Total Atom Upgrade LV": 3,
  "Total Construct Buildings LV": 4,
  "Equinox Clouds Completed": null,
  "Most Greenstacks in Storage": 3,
  "Total Cooking Meals LV": 3,
  "Total Kitchen Upgrade LV": 3,
  "Highest Power Mob": 3,
  "Fastest Time reaching Round 100 Arena (in Seconds)": 3,
  "Total Shiny Mob LV": 9,
  "Total Mob Breedability LV": null,
  "Total Lab Chips Owned": 4,
  "Rift Levels Completed": null,
  "Total Onyx Statues": null,
  "Total Artifacts Found": null,
  "Total Boat Upgrade LV": 3,
  "Gold Bar Sailing Treasure Owned": 3,
  "Highest Captain LV": 4,
  "Most Gaming Bits Owned": 3,
  "Total Gaming Plants Evolved": null,
  "Best Gold Nugget": 3,
  "Highest Immortal Snail LV": 9,
  "Rat King Crowns Reclaimed": 3,
  "God Rank in Divinity": 3,
  "Fastest Time to Kill 200 Tremor Wurms (in Seconds)": 3,
  "Total Opals Found": 3,
  "Total LV of Cavern Villagers": 3,
  "Total Digits of all Cavern Resources": 3,
  "Total Resource Layers Destroyed": 3,
  "Best Dawg Den score": 3,
  "Best Bravery Monument Round": 3,
  "Best Justice Monument Round": 5,
  "Best Wisdom Monument Round": null,
  "Total Gambit Time (in Seconds)": 3,
  "Best Pure Memory Round Reached": null,
  "Total Crops Discovered": null,
  "Total Golden Food Beanstacks": null,
  "Highest Crop OG": 5,
  "Total Land Rank": 3,
  "Largest Magic Bean Trade": null,
  "Farming Stickers Found": 3,
  "Ninja Floors Unlocked": null,
  "Jade Emporium Upgrades Purchased": 9,
  "Total Ninja Knowledge Upgrades LV": 3,
  "Total Career Summoning Wins": 3,
  "Total Summoning Upgrades LV": 3,
  "Familiars Owned in Summoning": 4,
  "Total Summoning Boss Stone victories": 3,
  "Most DMG Dealt to Gravestone in a Weekly Battle": 9,
  "Most Tottoise in Storage": 4,
  "Best Deathbringer Max Damage in Wraith Mode": 3,
  "Best Windwalker Max Damage in Tempest Mode": 3,
  "Best Arcane Cultist Max Damage in Arcanist Mode": 3,
  "Spirited Valley Emperor Boss Kills": null,
  "Total Coral Reef upgrades": null,
  "Total Spelunk Shop Upgrades LV": 3,
  "Total Spelunk Discoveries made": null,
  "Deepest Depth reached in a single Delve": 3,
  "Biggest Haul in a single Delve": 3,
  "Highest leveled Spelunker": 3,
  "Minehead Opponents Defeated": 3,
  "Total Research Grid Upgrades": null,
  "Total Glimbo Trades": 3,
  "Unique Sushi Created": null,
  "Button Presses": 3,
};
