// Hardcoded list IT uses to count Career Summoning Wins.
//
// IT's calcTomeQuantity for task #98 does:
//   allBattles[0] = 9 white battles (whiteBattleOrder mapped to Pet IDs)
//   allBattles[1..9] = deathNote enemies grouped by world
//   totalWins = count of (whiteBattleOrder ∪ deathNote.rawName) ∩ Summon[1]
//              + highestEndlessLevel (OptLacc[319])
//
// Source: IdleonToolbox/parsers/world-6/summoning.ts (parseSummoning) and
// IdleonToolbox/data/website-data.json (deathNote array). Generated by
// scripts/extract-summoning-enemies.ts.

export const SUMMONING_ENEMY_IDS: readonly string[] = [
  // 9 white battles (whiteBattleOrder)
  "Pet1", "Pet2", "Pet3", "Pet0", "Pet4", "Pet6", "Pet5", "Pet10", "Pet11",
  // 99 deathNote enemies (across worlds 0..7)
  "mushG", "mushR", "frogG", "beanG", "slimeG", "snakeG", "carrotO",
  "goblinG", "plank", "frogBIG", "poopSmall", "ratB", "branch", "acorn",
  "mushW", "jarSand", "mimicA", "crabcake", "coconut", "sandcastle",
  "pincermin", "potato", "steak", "moonman", "sandgiant", "snailZ",
  "sheep", "flake", "stache", "bloque", "mamoth", "snowball", "penguin",
  "thermostat", "glass", "snakeB", "speaker", "eye", "ram", "skele2",
  "mushP", "w4a2", "w4a3", "demonP", "w4b2", "w4b1", "w4b3", "w4b4",
  "w4b5", "w4c1", "w4c2", "w4c3", "w4c4",
  "w5a1", "w5a2", "w5a3", "w5a4", "w5a5", "w5b1", "w5b2", "w5b3", "w5b4",
  "w5b5", "w5b6", "w5c1", "w5c2",
  "w6a1", "w6a2", "w6a3", "w6a4", "w6a5", "w6b1", "w6b2", "w6b3", "w6b4",
  "w6c1", "w6c2", "w6d1", "w6d2", "w6d3",
  "w7a1", "w7a2", "w7a3", "w7a4", "w7a5", "w7a6", "w7a7", "w7a8", "w7a9",
  "w7a10", "w7a11", "w7a12",
  "w7b1", "w7b2", "w7b3", "w7b4", "w7b5", "w7b6", "w7b7",
];

export const SUMMONING_ENEMY_SET = new Set(SUMMONING_ENEMY_IDS);
