// Top-player Coin Multi reference — best-of-each-source pools run through
// ONE combine() pass (the same coin math a real save uses), gated PER CLASS
// for the coin formula's class talents. Use topCoinFlatForClass(classKey).
// Large file: lazy-load it, don't import statically.
// Generated 2026-09-23T19:18:02.894Z · 81 players. Refresh: scripts/update-top-coin.ts.

type FlatMap = Readonly<Record<string, number>>;

export const TOP_COIN_FLAT: FlatMap = {
    "Coin Multi": 1.2744639999468838e+40,
    "Coin Multi / ⛪ Divinity · Crop Depot": 374.2109981359871,
    "Coin Multi / ⛪ Divinity · Crop Depot / Crop Depot Bonus 4 (Cash)": 31695.283563704077,
    "Coin Multi / ⛪ Divinity · Crop Depot / Crop Depot Bonus 4 (Cash) / Crops found": 330,
    "Coin Multi / ⛪ Divinity · Crop Depot / Crop Depot Bonus 4 (Cash) / Depot multi": 6.403087588627086,
    "Coin Multi / ⛪ Divinity · Crop Depot / Crop Depot Bonus 4 (Cash) / Emporium 23 unlocked": 1,
    "Coin Multi / ⛪ Divinity · Crop Depot / Divinity minor bonus (Cash)": 5625.816249894633,
    "Coin Multi / ➕ Additive Pool": 2210.296678916437,
    "Coin Multi / ➕ Additive Pool / American Tipper (Talent 644)": 1788.2862985685072,
    "Coin Multi / ➕ Additive Pool / American Tipper (Talent 644) / Active": 1,
    "Coin Multi / ➕ Additive Pool / American Tipper (Talent 644) / Cooking LV / 10": 28.1,
    "Coin Multi / ➕ Additive Pool / American Tipper (Talent 644) / Level": 389,
    "Coin Multi / ➕ Additive Pool / American Tipper (Talent 644) / Max Level": 396,
    "Coin Multi / ➕ Additive Pool / American Tipper (Talent 644) / Talent Value": 63.640081799591,
    "Coin Multi / ➕ Additive Pool / Cash From Mobs Arcade Bonus (Arcade 10)": 40.19900497512438,
    "Coin Multi / ➕ Additive Pool / Cash From Mobs Arcade Bonus (Arcade 10) / Companion 27 Multi": 2,
    "Coin Multi / ➕ Additive Pool / Cash From Mobs Arcade Bonus (Arcade 10) / Maxed Multi (101)": 2,
    "Coin Multi / ➕ Additive Pool / Cash From Mobs Arcade Bonus (Arcade 10) / Raw (lv=101)": 10.049751243781095,
    "Coin Multi / ➕ Additive Pool / Cash From Mobs Arcade Bonus (Arcade 11)": 60.298507462686565,
    "Coin Multi / ➕ Additive Pool / Cash From Mobs Arcade Bonus (Arcade 11) / Companion 27 Multi": 2,
    "Coin Multi / ➕ Additive Pool / Cash From Mobs Arcade Bonus (Arcade 11) / Maxed Multi (101)": 2,
    "Coin Multi / ➕ Additive Pool / Cash From Mobs Arcade Bonus (Arcade 11) / Raw (lv=101)": 15.074626865671641,
    "Coin Multi / ➕ Additive Pool / Cash Money (Talent 657)": 46.666666666666664,
    "Coin Multi / ➕ Additive Pool / Cash Money (Talent 657) / Active": 1,
    "Coin Multi / ➕ Additive Pool / Cash Money (Talent 657) / Level": 100,
    "Coin Multi / ➕ Additive Pool / Cash Money (Talent 657) / Max Level": 100,
    "Coin Multi / ➕ Additive Pool / Cash Vial (MonsterCash)": 104.51999999999998,
    "Coin Multi / ➕ Additive Pool / Cash Vial (MonsterCash) / DIETER_DRINK": 104.51999999999998,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22)": 0,
    "Coin Multi / ➕ Additive Pool / Coins For Charon (Talent 643)": 544.9353448275863,
    "Coin Multi / ➕ Additive Pool / Coins For Charon (Talent 643) / Active": 1,
    "Coin Multi / ➕ Additive Pool / Coins For Charon (Talent 643) / Level": 389,
    "Coin Multi / ➕ Additive Pool / Coins For Charon (Talent 643) / Max Level": 396,
    "Coin Multi / ➕ Additive Pool / Coins For Charon (Talent 643) / Multikill Damage Tier": 1,
    "Coin Multi / ➕ Additive Pool / Coins For Charon (Talent 643) / Multikill tier (selected map)": 26,
    "Coin Multi / ➕ Additive Pool / Coins For Charon (Talent 643) / Talent Value": 20.959051724137932,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3)": 2300.493678954736,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Equipment Bonuses": 213,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Equipment Bonuses / CatchingNet11": 15,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Equipment Bonuses / EquipmentHats105": 35,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Equipment Bonuses / EquipmentKeychain29": 30,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Equipment Bonuses / EquipmentKeychain29#1": 30,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Equipment Bonuses / EquipmentPants29": 22,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Equipment Bonuses / EquipmentShirts37": 26,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Equipment Bonuses / EquipmentShoes37": 25,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Equipment Bonuses / EquipmentTools14": 10,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Equipment Bonuses / EquipmentToolsHatchet12": 10,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Equipment Bonuses / FishingRod11": 10,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Hatrack Bonuses": 93.6,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Hatrack Bonuses / Honker Hat": 41.6,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Hatrack Bonuses / Honker Hat / Base": 20,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Hatrack Bonuses / Honker Hat / Hatrack Bonus Multi": 2.08,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Hatrack Bonuses / Honker Hat / Hatrack Bonus Multi / Abalone Sashimi (Sushi Tier 37) — Hat Rack Multi (RoG Bonus 36)": 1,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Hatrack Bonuses / Honker Hat / Hatrack Bonus Multi / Hatrack Boutique Bonus (Event Shop 30)": 10,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Hatrack Bonuses / Honker Hat / Hatrack Bonus Multi / Hats Owned": 82,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Hatrack Bonuses / Honker Hat / Hatrack Bonus Multi / Wild Boar (Companion 31)": 15,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Hatrack Bonuses / Ice Cream Sundae": 52,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Hatrack Bonuses / Ice Cream Sundae / Base": 25,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Hatrack Bonuses / Ice Cream Sundae / Hatrack Bonus Multi": 2.08,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Hatrack Bonuses / Ice Cream Sundae / Hatrack Bonus Multi / Abalone Sashimi (Sushi Tier 37) — Hat Rack Multi (RoG Bonus 36)": 1,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Hatrack Bonuses / Ice Cream Sundae / Hatrack Bonus Multi / Hatrack Boutique Bonus (Event Shop 30)": 10,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Hatrack Bonuses / Ice Cream Sundae / Hatrack Bonus Multi / Hats Owned": 82,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Hatrack Bonuses / Ice Cream Sundae / Hatrack Bonus Multi / Wild Boar (Companion 31)": 15,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses": 1794.7358723751745,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Lovely Day Nametag": 1087.7187105304088,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Lovely Day Nametag / Base": 200,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Lovely Day Nametag / Gallery Bonus Multi": 2.175437421060818,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Lovely Day Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49)": 50,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Lovely Day Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49) / Bonus": 50,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Lovely Day Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49) / Owned": 1,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Lovely Day Nametag / Gallery Bonus Multi / Codfrey Rulz OK (Bubble Y13, capped 20)": 17.514144823209378,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Lovely Day Nametag / Gallery Bonus Multi / Coralcave Crab (Card w7a11, capped 10)": 7,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Lovely Day Nametag / Gallery Bonus Multi / Dulce Vitiri (Sushi Tier 55) — Gallery Bonus Multi (RoG Bonus 54)": 1,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Lovely Day Nametag / Gallery Bonus Multi / Gallery Level": 30,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Lovely Day Nametag / Gallery Bonus Multi / Gallery Level / Level": 10,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Lovely Day Nametag / Gallery Bonus Multi / Glasstic Brain (Clam Work 7)": 3,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Lovely Day Nametag / Gallery Bonus Multi / Skull Shop Tier 3 (Killroy 3)": 9.029597282872393,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Lovely Day Nametag / Level": 5,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Lovely Day Nametag / Tier": 2.5,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Pot of Gold Nametag": 543.8593552652044,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Pot of Gold Nametag / Base": 100,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Pot of Gold Nametag / Gallery Bonus Multi": 2.175437421060818,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Pot of Gold Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49)": 50,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Pot of Gold Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49) / Bonus": 50,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Pot of Gold Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49) / Owned": 1,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Pot of Gold Nametag / Gallery Bonus Multi / Codfrey Rulz OK (Bubble Y13, capped 20)": 17.514144823209378,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Pot of Gold Nametag / Gallery Bonus Multi / Coralcave Crab (Card w7a11, capped 10)": 7,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Pot of Gold Nametag / Gallery Bonus Multi / Dulce Vitiri (Sushi Tier 55) — Gallery Bonus Multi (RoG Bonus 54)": 1,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Pot of Gold Nametag / Gallery Bonus Multi / Gallery Level": 30,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Pot of Gold Nametag / Gallery Bonus Multi / Gallery Level / Level": 10,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Pot of Gold Nametag / Gallery Bonus Multi / Glasstic Brain (Clam Work 7)": 3,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Pot of Gold Nametag / Gallery Bonus Multi / Skull Shop Tier 3 (Killroy 3)": 9.029597282872393,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Pot of Gold Nametag / Level": 5,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Pot of Gold Nametag / Tier": 2.5,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Tome Apprentice Nametag": 27.19296776326022,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Tome Apprentice Nametag / Base": 5,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Tome Apprentice Nametag / Gallery Bonus Multi": 2.175437421060818,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Tome Apprentice Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49)": 50,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Tome Apprentice Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49) / Bonus": 50,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Tome Apprentice Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49) / Owned": 1,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Tome Apprentice Nametag / Gallery Bonus Multi / Codfrey Rulz OK (Bubble Y13, capped 20)": 17.514144823209378,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Tome Apprentice Nametag / Gallery Bonus Multi / Coralcave Crab (Card w7a11, capped 10)": 7,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Tome Apprentice Nametag / Gallery Bonus Multi / Dulce Vitiri (Sushi Tier 55) — Gallery Bonus Multi (RoG Bonus 54)": 1,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Tome Apprentice Nametag / Gallery Bonus Multi / Gallery Level": 30,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Tome Apprentice Nametag / Gallery Bonus Multi / Gallery Level / Level": 10,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Tome Apprentice Nametag / Gallery Bonus Multi / Glasstic Brain (Clam Work 7)": 3,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Tome Apprentice Nametag / Gallery Bonus Multi / Skull Shop Tier 3 (Killroy 3)": 9.029597282872393,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Tome Apprentice Nametag / Level": 11,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Tome Apprentice Nametag / Tier": 2.5,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Treasure Nametag": 135.9648388163011,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Treasure Nametag / Base": 25,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Treasure Nametag / Gallery Bonus Multi": 2.175437421060818,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Treasure Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49)": 50,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Treasure Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49) / Bonus": 50,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Treasure Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49) / Owned": 1,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Treasure Nametag / Gallery Bonus Multi / Codfrey Rulz OK (Bubble Y13, capped 20)": 17.514144823209378,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Treasure Nametag / Gallery Bonus Multi / Coralcave Crab (Card w7a11, capped 10)": 7,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Treasure Nametag / Gallery Bonus Multi / Dulce Vitiri (Sushi Tier 55) — Gallery Bonus Multi (RoG Bonus 54)": 1,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Treasure Nametag / Gallery Bonus Multi / Gallery Level": 30,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Treasure Nametag / Gallery Bonus Multi / Gallery Level / Level": 10,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Treasure Nametag / Gallery Bonus Multi / Glasstic Brain (Clam Work 7)": 3,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Treasure Nametag / Gallery Bonus Multi / Skull Shop Tier 3 (Killroy 3)": 9.029597282872393,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Treasure Nametag / Level": 8,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Nametag Bonuses / Treasure Nametag / Tier": 2.5,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Obol Bonuses": 36,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Obol Bonuses / Personal": 36,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Obol Bonuses / Personal / ObolSilverMoney × 6": 36,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Obol Bonuses / Personal / ObolSilverMoney × 6 / Slot 0": 6,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Obol Bonuses / Personal / ObolSilverMoney × 6 / Slot 11": 6,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Obol Bonuses / Personal / ObolSilverMoney × 6 / Slot 18": 6,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Obol Bonuses / Personal / ObolSilverMoney × 6 / Slot 20": 6,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Obol Bonuses / Personal / ObolSilverMoney × 6 / Slot 4": 6,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Obol Bonuses / Personal / ObolSilverMoney × 6 / Slot 9": 6,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Trophy Bonuses": 163.15780657956134,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Trophy Bonuses / Beach Bro": 163.15780657956134,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Trophy Bonuses / Beach Bro / Base": 50,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Trophy Bonuses / Beach Bro / Gallery Bonus Multi": 2.175437421060818,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Trophy Bonuses / Beach Bro / Gallery Bonus Multi / Bubba The Seal (Companion 49)": 50,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Trophy Bonuses / Beach Bro / Gallery Bonus Multi / Bubba The Seal (Companion 49) / Bonus": 50,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Trophy Bonuses / Beach Bro / Gallery Bonus Multi / Bubba The Seal (Companion 49) / Owned": 1,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Trophy Bonuses / Beach Bro / Gallery Bonus Multi / Codfrey Rulz OK (Bubble Y13, capped 20)": 17.514144823209378,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Trophy Bonuses / Beach Bro / Gallery Bonus Multi / Coralcave Crab (Card w7a11, capped 10)": 7,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Trophy Bonuses / Beach Bro / Gallery Bonus Multi / Dulce Vitiri (Sushi Tier 55) — Gallery Bonus Multi (RoG Bonus 54)": 1,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Trophy Bonuses / Beach Bro / Gallery Bonus Multi / Gallery Level": 30,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Trophy Bonuses / Beach Bro / Gallery Bonus Multi / Gallery Level / Level": 10,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Trophy Bonuses / Beach Bro / Gallery Bonus Multi / Glasstic Brain (Clam Work 7)": 3,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Trophy Bonuses / Beach Bro / Gallery Bonus Multi / Skull Shop Tier 3 (Killroy 3)": 9.029597282872393,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Trophy Bonuses / Beach Bro / Slot": 62,
    "Coin Multi / ➕ Additive Pool / EtcBonuses(3) (etcBonus 3) / Trophy Bonuses / Beach Bro / Tier": 1.5,
    "Coin Multi / ➕ Additive Pool / Flurbo Shop 4 (Monster Cash)": 25,
    "Coin Multi / ➕ Additive Pool / Flurbo Shop 4 (Monster Cash) / Level": 50,
    "Coin Multi / ➕ Additive Pool / Golden Food (MonsterCash)": 184812.38388882793,
    "Coin Multi / ➕ Additive Pool / Guild 8 × World": 116.66666666666667,
    "Coin Multi / ➕ Additive Pool / Guild 8 × World / 1 + ⌊map / 50⌋": 7,
    "Coin Multi / ➕ Additive Pool / Guild 8 × World / Guild 8": 16.666666666666668,
    "Coin Multi / ➕ Additive Pool / Guild 8 × World / Guild 8 / Formula Result": 16.666666666666668,
    "Coin Multi / ➕ Additive Pool / Guild 8 × World / Guild 8 / Guild Points": 100,
    "Coin Multi / ➕ Additive Pool / Molti (Card w5b1) × 7": 49,
    "Coin Multi / ➕ Additive Pool / Molti (Card w5b1) × 7 / Card Lv": 7,
    "Coin Multi / ➕ Additive Pool / Money Cards (Card Type 11)": 490,
    "Coin Multi / ➕ Additive Pool / Money Cards (Card Type 11) / Boss5C Lv7": 220.5,
    "Coin Multi / ➕ Additive Pool / Money Cards (Card Type 11) / babayaga Lv7": 122.5,
    "Coin Multi / ➕ Additive Pool / Money Cards (Card Type 11) / mini3a Lv7": 147,
    "Coin Multi / ➕ Additive Pool / Ninja Extra Cash (OLA[420])": 447,
    "Coin Multi / ➕ Additive Pool / Post Office 13c": 23.4,
    "Coin Multi / ➕ Additive Pool / Post Office 13c / Utilitarian_Capsule slot2": 23.4,
    "Coin Multi / ➕ Additive Pool / Summoning Im (Achievement 376) × 20": 20,
    "Coin Multi / ➕ Additive Pool / Valley Visitor (Achievement 350) × 10": 10,
    "Coin Multi / ➕ Additive Pool / Vault 14 × VaultKillzTotal(4)": 3366,
    "Coin Multi / ➕ Additive Pool / Vault 14 × VaultKillzTotal(4) / Vault 14": 198,
    "Coin Multi / ➕ Additive Pool / Vault 14 × VaultKillzTotal(4) / VaultKillzTotal(4)": 17,
    "Coin Multi / ➕ Additive Pool / Vault 17 × log(OLA[340])": 9820.097834693832,
    "Coin Multi / ➕ Additive Pool / Vault 17 × log(OLA[340]) / Vault 17": 426.8,
    "Coin Multi / ➕ Additive Pool / Vault 17 × log(OLA[340]) / log10(OLA[340])": 23.00866409253475,
    "Coin Multi / ➕ Additive Pool / Vault 2": 4990.92,
    "Coin Multi / ➕ Additive Pool / Vault 31 × VaultKillzTotal(7)": 2228.8,
    "Coin Multi / ➕ Additive Pool / Vault 31 × VaultKillzTotal(7) / Vault 31": 139.3,
    "Coin Multi / ➕ Additive Pool / Vault 31 × VaultKillzTotal(7) / VaultKillzTotal(7)": 16,
    "Coin Multi / ➕ Additive Pool / Vault 70 × cards collected": 9640,
    "Coin Multi / ➕ Additive Pool / Vault 70 × cards collected / Cards collected": 241,
    "Coin Multi / ➕ Additive Pool / Vault 70 × cards collected / Vault 70": 40,
    "Coin Multi / ➕ Additive Pool / Zero G Scorin' (Achievement 235) × 5": 5,
    "Coin Multi / 🌟 Pristine Charm 16": 1.4,
    "Coin Multi / 🌟 Pristine Charm 16 / Pristine 16": 40,
    "Coin Multi / 🌪️ Dust Walker": 6.007716896665547,
    "Coin Multi / 🌪️ Dust Walker / Dustwalker (Talent 433) × log(OLA[362])": 500.7716896665547,
    "Coin Multi / 🌪️ Dust Walker / Dustwalker (Talent 433) × log(OLA[362]) / Talent 433 (getbonus2, min 1)": 22.84351145038168,
    "Coin Multi / 🌪️ Dust Walker / Dustwalker (Talent 433) × log(OLA[362]) / log10(OLA[362])": 21.9218350363638,
    "Coin Multi / 🍣 Sushi 18": 1.2,
    "Coin Multi / 🍣 Sushi 18 / Tobo Twins (Sushi Tier 19) — extra coins dropped by monsters (RoG Bonus 18)": 20,
    "Coin Multi / 🍣 Sushi 18 / Tobo Twins (Sushi Tier 19) — extra coins dropped by monsters (RoG Bonus 18) / RoG Value": 20,
    "Coin Multi / 🍣 Sushi 18 / Tobo Twins (Sushi Tier 19) — extra coins dropped by monsters (RoG Bonus 18) / Unique Sushi": 40,
    "Coin Multi / 🍣 Sushi 37": 1.4,
    "Coin Multi / 🍣 Sushi 37 / Aji Sashimi (Sushi Tier 38) — extra coins dropped by monsters (RoG Bonus 37)": 40,
    "Coin Multi / 🍣 Sushi 37 / Aji Sashimi (Sushi Tier 38) — extra coins dropped by monsters (RoG Bonus 37) / RoG Value": 40,
    "Coin Multi / 🍣 Sushi 37 / Aji Sashimi (Sushi Tier 38) — extra coins dropped by monsters (RoG Bonus 37) / Unique Sushi": 40,
    "Coin Multi / 🍽️ Meal · Artifact · Roo · Vote": 3456.297020027351,
    "Coin Multi / 🍽️ Meal · Artifact · Roo · Vote / Artifact 1 × highest level": 23100,
    "Coin Multi / 🍽️ Meal · Artifact · Roo · Vote / Artifact 1 × highest level / Artifact bonus": 12,
    "Coin Multi / 🍽️ Meal · Artifact · Roo · Vote / Artifact 1 × highest level / Highest char level": 1925,
    "Coin Multi / 🍽️ Meal · Artifact · Roo · Vote / Kangaroo Cash (Roo 6)": 9207,
    "Coin Multi / 🍽️ Meal · Artifact · Roo · Vote / Kangaroo Cash (Roo 6) / Companion 51": 2,
    "Coin Multi / 🍽️ Meal · Artifact · Roo · Vote / Kangaroo Cash (Roo 6) / Legend 26": 1000,
    "Coin Multi / 🍽️ Meal · Artifact · Roo · Vote / Kangaroo Cash (Roo 6) / Megafeathers %": 675,
    "Coin Multi / 🍽️ Meal · Artifact · Roo · Vote / Kangaroo Cash (Roo 6) / ⌈(OLA[271] − 6) / 7⌉": 12,
    "Coin Multi / 🍽️ Meal · Artifact · Roo · Vote / Meals (Cash)": 313222.7020027351,
    "Coin Multi / 🍽️ Meal · Artifact · Roo · Vote / Meals (Cash) / Meal 2 (Salad)": 86196.10145454002,
    "Coin Multi / 🍽️ Meal · Artifact · Roo · Vote / Meals (Cash) / Meal 31 (Bunt Cake)": 227026.60054819507,
    "Coin Multi / 🍽️ Meal · Artifact · Roo · Vote / Vote 34 (Cash)": 0,
    "Coin Multi / 🍽️ Meal · Artifact · Roo · Vote / Vote 34 (Cash) / Voting multi": 2.74,
    "Coin Multi / 🎁 Cash Bundle": 3.5,
    "Coin Multi / 🎁 Cash Bundle / Cash Bundle (bun_y)": 250,
    "Coin Multi / 🎁 Cash Bundle / Cash Bundle (bun_y) / Owned": 1,
    "Coin Multi / 🎰 Gambit": 1.7424692144159901,
    "Coin Multi / 🎰 Gambit / Gambit 7 (Cash)": 74.24692144159903,
    "Coin Multi / 🎰 Gambit / Gambit 7 (Cash) / Deathnote skulls (Measurement 13)": 2060,
    "Coin Multi / 🎰 Gambit / Gambit 7 (Cash) / Gambit points": 26589365.065022536,
    "Coin Multi / 🎽 Bonus Money Gear": 6.600764426152149,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77)": 560.0764426152149,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Equipment Bonuses": 400,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Equipment Bonuses / EquipmentPendant33": 400,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Equipment Bonuses / EquipmentPendant33 / Item Bonus (raw)": 200,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Equipment Bonuses / EquipmentPendant33 / Pendant Doubler (Lab Chip)": 2,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses": 74.55,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Festive Beast Mask": 31.95,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Festive Beast Mask / Base": 15,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Festive Beast Mask / Hatrack Bonus Multi": 2.13,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Festive Beast Mask / Hatrack Bonus Multi / Abalone Sashimi (Sushi Tier 37) — Hat Rack Multi (RoG Bonus 36)": 1,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Festive Beast Mask / Hatrack Bonus Multi / Hatrack Boutique Bonus (Event Shop 30)": 10,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Festive Beast Mask / Hatrack Bonus Multi / Hats Owned": 87,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Festive Beast Mask / Hatrack Bonus Multi / Wild Boar (Companion 31)": 15,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Paper Bag": 21.299999999999997,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Paper Bag / Base": 10,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Paper Bag / Hatrack Bonus Multi": 2.13,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Paper Bag / Hatrack Bonus Multi / Abalone Sashimi (Sushi Tier 37) — Hat Rack Multi (RoG Bonus 36)": 1,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Paper Bag / Hatrack Bonus Multi / Hatrack Boutique Bonus (Event Shop 30)": 10,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Paper Bag / Hatrack Bonus Multi / Hats Owned": 87,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Paper Bag / Hatrack Bonus Multi / Wild Boar (Companion 31)": 15,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Umbrella Brim": 21.299999999999997,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Umbrella Brim / Base": 10,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Umbrella Brim / Hatrack Bonus Multi": 2.13,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Umbrella Brim / Hatrack Bonus Multi / Abalone Sashimi (Sushi Tier 37) — Hat Rack Multi (RoG Bonus 36)": 1,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Umbrella Brim / Hatrack Bonus Multi / Hatrack Boutique Bonus (Event Shop 30)": 10,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Umbrella Brim / Hatrack Bonus Multi / Hats Owned": 87,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Hatrack Bonuses / Umbrella Brim / Hatrack Bonus Multi / Wild Boar (Companion 31)": 15,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses": 85.5264426152149,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses / Tome Pro Nametag": 85.5264426152149,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses / Tome Pro Nametag / Base": 15,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses / Tome Pro Nametag / Gallery Bonus Multi": 2.280705136405731,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses / Tome Pro Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49)": 50,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses / Tome Pro Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49) / Bonus": 50,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses / Tome Pro Nametag / Gallery Bonus Multi / Bubba The Seal (Companion 49) / Owned": 1,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses / Tome Pro Nametag / Gallery Bonus Multi / Codfrey Rulz OK (Bubble Y13, capped 20)": 17.447374390525994,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses / Tome Pro Nametag / Gallery Bonus Multi / Coralcave Crab (Card w7a11, capped 10)": 7,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses / Tome Pro Nametag / Gallery Bonus Multi / Dulce Vitiri (Sushi Tier 55) — Gallery Bonus Multi (RoG Bonus 54)": 1,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses / Tome Pro Nametag / Gallery Bonus Multi / Gallery Level": 30,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses / Tome Pro Nametag / Gallery Bonus Multi / Gallery Level / Level": 10,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses / Tome Pro Nametag / Gallery Bonus Multi / Glasstic Brain (Clam Work 7)": 3,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses / Tome Pro Nametag / Gallery Bonus Multi / Silkrode Motherboard (Chip 16)": 10,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses / Tome Pro Nametag / Gallery Bonus Multi / Skull Shop Tier 3 (Killroy 3)": 9.623139250047108,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses / Tome Pro Nametag / Level": 11,
    "Coin Multi / 🎽 Bonus Money Gear / EtcBonuses(77) (etcBonus 77) / Nametag Bonuses / Tome Pro Nametag / Tier": 2.5,
    "Coin Multi / 🎽 Extra Money Gear": 6.7675,
    "Coin Multi / 🎽 Extra Money Gear / EtcBonuses(100) (etcBonus 100)": 576.75,
    "Coin Multi / 🎽 Extra Money Gear / EtcBonuses(100) (etcBonus 100) / Equipment Bonuses": 576.75,
    "Coin Multi / 🎽 Extra Money Gear / EtcBonuses(100) (etcBonus 100) / Equipment Bonuses / Corsair Uniform": 576.75,
    "Coin Multi / 🎽 Extra Money Gear / EtcBonuses(100) (etcBonus 100) / Equipment Bonuses / Corsair Uniform / Item Bonus (raw)": 300,
    "Coin Multi / 🎽 Extra Money Gear / EtcBonuses(100) (etcBonus 100) / Equipment Bonuses / Corsair Uniform / Well Dressed (Grid 172)": 1.9224999999999999,
    "Coin Multi / 🏟️ Arena · Friend · Statue": 169300.2973305004,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Friend Bonus": 117.32987312572087,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Friend Bonus / Cheesus1": 46.93194925028835,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Friend Bonus / Cheesus1 / Score": 19212,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Friend Bonus / Mr Pig (Companion 30)": 2.5,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Friend Bonus / Mr Pig (Companion 30) / Bonus": 2.5,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Friend Bonus / Mr Pig (Companion 30) / Owned": 1,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Pet Arena bonus 14": 1,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Pet Arena bonus 14 / Arena wave (OLA[89])": 209,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Pet Arena bonus 14 / Wave needed": 175,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Pet Arena bonus 5 (×0.5)": 0.5,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Pet Arena bonus 5 (×0.5) / Arena wave (OLA[89])": 209,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Pet Arena bonus 5 (×0.5) / Wave needed": 20,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Statue 19 ÷ 100": 169180.4674573747,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Statue 19 ÷ 100 / Statue bonus": 16918046.74573747,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Statue 19 ÷ 100 / Statue bonus / Base/Lv": 1,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Statue 19 ÷ 100 / Statue bonus / EventShop 19": 1,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Statue 19 ÷ 100 / Statue bonus / Gold G2": 3.8,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Statue 19 ÷ 100 / Statue bonus / Gold G3": 4,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Statue 19 ÷ 100 / Statue bonus / Level": 593,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Statue 19 ÷ 100 / Statue bonus / Meritoc 26": 225.0995024875622,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Statue 19 ÷ 100 / Statue bonus / Statue 29 multi": 18969.928983645532,
    "Coin Multi / 🏟️ Arena · Friend · Statue / Statue 19 ÷ 100 / Statue bonus / Talent 56": 132.88590604026845,
    "Coin Multi / 🐾 Coin Drop Multi": 4,
    "Coin Multi / 🐾 Coin Drop Multi / Balloonfish (Companion 38)": 3,
    "Coin Multi / 🐾 Companion 159": 2.5,
    "Coin Multi / 🐾 Companion 159 / Potluck (Companion 159)": 1.5,
    "Coin Multi / 🐾 Companion 24": 5,
    "Coin Multi / 🐾 Companion 24 / Cool Bird (Companion 24)": 5,
    "Coin Multi / 🐾 Companion 45": 1.5,
    "Coin Multi / 🐾 Companion 45 / Equinox Broadbass (Companion 45)": 0.5,
    "Coin Multi / 💻 Lab · Vault Kills": 721442008766.538,
    "Coin Multi / 💻 Lab · Vault Kills / Lab Mainframe 9 × green mushroom kills": 72144200319919.4,
    "Coin Multi / 💻 Lab · Vault Kills / Lab Mainframe 9 × green mushroom kills / Kills / 1e6": 20040055644422.06,
    "Coin Multi / 💻 Lab · Vault Kills / Lab Mainframe 9 × green mushroom kills / Mainframe 9": 3.6,
    "Coin Multi / 💻 Lab · Vault Kills / Vault 34 × VaultKillzTotal(8)": 12729.6,
    "Coin Multi / 💻 Lab · Vault Kills / Vault 34 × VaultKillzTotal(8) / Vault 34": 122.4,
    "Coin Multi / 💻 Lab · Vault Kills / Vault 34 × VaultKillzTotal(8) / VaultKillzTotal(8)": 104,
    "Coin Multi / 💻 Lab · Vault Kills / Vault 37 × VaultKillzTotal(9)": 543904.7999999999,
    "Coin Multi / 💻 Lab · Vault Kills / Vault 37 × VaultKillzTotal(9) / Vault 37": 40.8,
    "Coin Multi / 💻 Lab · Vault Kills / Vault 37 × VaultKillzTotal(9) / VaultKillzTotal(9)": 13331,
    "Coin Multi / 🔬 Research Grid": 1.64575,
    "Coin Multi / 🔬 Research Grid / Research Grid 149": 27.675,
    "Coin Multi / 🔬 Research Grid / Research Grid 169": 36.9,
    "Coin Multi / 🙏 Jawbreaker Prayer": 3.36,
    "Coin Multi / 🙏 Jawbreaker Prayer / Jawbreaker (Prayer 8)": 236,
    "Coin Multi / 🙏 Jawbreaker Prayer / Jawbreaker (Prayer 8) / Base Bonus": 40,
    "Coin Multi / 🙏 Jawbreaker Prayer / Jawbreaker (Prayer 8) / Level Scale": 5.9,
    "Coin Multi / 🙏 Jawbreaker Prayer / Jawbreaker (Prayer 8) / Prayer Lv": 50,
    "Coin Multi / 🛍️ Event Shop 20": 1.6,
    "Coin Multi / 🛍️ Event Shop 20 / Event Shop 20 (×0.6)": 0.6,
    "Coin Multi / 🛍️ Event Shop 20 / Event Shop 20 (×0.6) / Owned": 1,
    "Coin Multi / 🛍️ Event Shop 9": 1.5,
    "Coin Multi / 🛍️ Event Shop 9 / Event Shop 9 (×0.5)": 0.5,
    "Coin Multi / 🛍️ Event Shop 9 / Event Shop 9 (×0.5) / Owned": 1,
    "Coin Multi / 🧰 Gold Set": 1.5,
    "Coin Multi / 🧰 Gold Set / Gold Set": 50,
    "Coin Multi / 🧰 Gold Set / Gold Set / Bonus Value": 50,
    "Coin Multi / 🧰 Gold Set / Gold Set / GOLD_SET Unlocked": 1,
    "Coin Multi / 🫧 Cash Bubbles": 6350689.958971892,
    "Coin Multi / 🫧 Cash Bubbles / Dollar of Agility (CashAGI)": 203622247.6072192,
    "Coin Multi / 🫧 Cash Bubbles / Dollar of Agility (CashAGI) / Bubble": 676.5960159867194,
    "Coin Multi / 🫧 Cash Bubbles / Dollar of Agility (CashAGI) / Bubble / Base": 17.946698252887177,
    "Coin Multi / 🫧 Cash Bubbles / Dollar of Agility (CashAGI) / Bubble / Gpassz": 10.628345377484614,
    "Coin Multi / 🫧 Cash Bubbles / Dollar of Agility (CashAGI) / Bubble / Level": 10101,
    "Coin Multi / 🫧 Cash Bubbles / Dollar of Agility (CashAGI) / Bubble / Prisma": 3.5471472435360822,
    "Coin Multi / 🫧 Cash Bubbles / Dollar of Agility (CashAGI) / Total AGI": 75237873,
    "Coin Multi / 🫧 Cash Bubbles / Dollar of Agility (CashAGI) / ⌊AGI / 250⌋": 300951,
    "Coin Multi / 🫧 Cash Bubbles / Nickel of Wisdom (CashWIS)": 198980913.2309627,
    "Coin Multi / 🫧 Cash Bubbles / Nickel of Wisdom (CashWIS) / Bubble": 677.2388916414669,
    "Coin Multi / 🫧 Cash Bubbles / Nickel of Wisdom (CashWIS) / Bubble / Base": 17.96422893481717,
    "Coin Multi / 🫧 Cash Bubbles / Nickel of Wisdom (CashWIS) / Bubble / Level": 15066,
    "Coin Multi / 🫧 Cash Bubbles / Nickel of Wisdom (CashWIS) / Bubble / Ppassz": 10.628062327909333,
    "Coin Multi / 🫧 Cash Bubbles / Nickel of Wisdom (CashWIS) / Bubble / Prisma": 3.5471472435360822,
    "Coin Multi / 🫧 Cash Bubbles / Nickel of Wisdom (CashWIS) / Total WIS": 73453146,
    "Coin Multi / 🫧 Cash Bubbles / Nickel of Wisdom (CashWIS) / ⌊WIS / 250⌋": 293812,
    "Coin Multi / 🫧 Cash Bubbles / Penny of Strength (CashSTR)": 232465735.0590072,
    "Coin Multi / 🫧 Cash Bubbles / Penny of Strength (CashSTR) / Bubble": 677.1523804584551,
    "Coin Multi / 🫧 Cash Bubbles / Penny of Strength (CashSTR) / Bubble / Base": 17.955183002738817,
    "Coin Multi / 🫧 Cash Bubbles / Penny of Strength (CashSTR) / Bubble / Level": 12019,
    "Coin Multi / 🫧 Cash Bubbles / Penny of Strength (CashSTR) / Bubble / Opassz": 10.632058487893287,
    "Coin Multi / 🫧 Cash Bubbles / Penny of Strength (CashSTR) / Bubble / Prisma": 3.5471472435360822,
    "Coin Multi / 🫧 Cash Bubbles / Penny of Strength (CashSTR) / Total STR": 85824800,
    "Coin Multi / 🫧 Cash Bubbles / Penny of Strength (CashSTR) / ⌊STR / 250⌋": 343299,
  };

export const TOP_COIN_PROFILE_OVERRIDES: Readonly<Record<string, FlatMap>> = {
  "t22": {
    "Coin Multi": 1.2747138613064826e+40,
    "Coin Multi / ➕ Additive Pool": 2210.7300122497704,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22)": 43.333333333333336,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Active": 1,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level": 650,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level": 396,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap": 396,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Base Level (N.js literal)": 100,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Checkout Takeout Achievement": 5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Lv 1 Oxygen Atom": 10,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Lv 1 Oxygen Atom / Atom 7 Lv": 70,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Salt Lick 4": 20,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Salt Lick 4 / Per Lv": 2,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Salt Lick 4 / Salt Lick 4 Lv": 10,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Sovereign Fury Relic": 150,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Sovereign Fury Relic / Artifact 21 Base": 25,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Sovereign Fury Relic / Artifact 21 Tier": 6,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19": 75.621,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Higher Bonus Multi": 1.9500000000000002,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Higher Bonus Multi / Crystal Comb Pristine Charm": 1.3,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Higher Bonus Multi / Crystal Comb Pristine Charm / Pristine 8 Bonus": 30,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Higher Bonus Multi / Gem Shop Multi": 1.5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Higher Bonus Multi / Gem Shop Multi / Gem Items 11": 5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Summoning Battles": 14,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Summoning Battles / Cyan": 10.5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Summoning Battles / Cyan / Battle 14": 10.5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Summoning Battles / Teal": 3.5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Summoning Battles / Teal / Battle 9": 3.5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined)": 2.77,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Godshard Set": 15,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Regalis Achievement (379)": 1,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Sovereign Winz Lantern": 150,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Sovereign Winz Lantern / Artifact 32 Base": 25,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Sovereign Winz Lantern / Artifact 32 Tier": 6,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Spectre Stars Achievement (373)": 1,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / W6 Merit Shop (Task)": 10,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / Talent Book Library Base": 25,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / W3 Merit Shop Unlock": 10,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / W3 Merit Shop Unlock / Per Point": 2,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Max Book Lv Cap / W3 Merit Shop Unlock / W3 Merit Points Spent": 5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Base Level / Points Invested": 409,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels": 241,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Divinity Minor 2 (Arctis)": 76,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Divinity Minor 2 (Arctis) / Bubble Y2 Active": 1.499896264842772,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Divinity Minor 2 (Arctis) / Coral Kid 3": 258,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Divinity Minor 2 (Arctis) / Divinity Lv": 820,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Divinity Minor 2 (Arctis) / God Minor X1(2)": 15,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Equinox Symbols (Dream 10)": 66,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Equinox Symbols (Dream 10) / Base Max": 5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Equinox Symbols (Dream 10) / Cloud 30 (×4)": 4,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Equinox Symbols (Dream 10) / Summoning WinBonus 24": 47,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Equinox Symbols (Dream 10) / Summoning WinBonus 24 / Endless Wins Bonus": 47,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Equinox Symbols (Dream 10) / Summoning WinBonus 24 / Endless Wins Bonus / Endless Wins Count": 376,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Equinox Symbols (Dream 10) / Summoning WinBonus 24 / Endless Wins Bonus / Per 40-Cycle Bonus": 5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Equinox Symbols (Dream 10) / Summoning WinBonus 24 / Normal Wins Bonus": 0,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Equinox Symbols (Dream 10) / SuperBit 35 (×10)": 10,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage)": 16,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Best Mage Lv": 1788,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Best Mage Lv / Char 1 Lv": 1788,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff": 1,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level": 0,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap": 396,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Base Level (N.js literal)": 100,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Checkout Takeout Achievement": 5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Lv 1 Oxygen Atom": 10,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Lv 1 Oxygen Atom / Atom 7 Lv": 70,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Salt Lick 4": 20,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Salt Lick 4 / Per Lv": 2,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Salt Lick 4 / Salt Lick 4 Lv": 10,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Sovereign Fury Relic": 150,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Sovereign Fury Relic / Artifact 21 Base": 25,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Sovereign Fury Relic / Artifact 21 Tier": 6,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19": 75.621,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Higher Bonus Multi": 1.9500000000000002,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Higher Bonus Multi / Crystal Comb Pristine Charm": 1.3,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Higher Bonus Multi / Crystal Comb Pristine Charm / Pristine 8 Bonus": 30,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Higher Bonus Multi / Gem Shop Multi": 1.5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Higher Bonus Multi / Gem Shop Multi / Gem Items 11": 5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Summoning Battles": 14,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Summoning Battles / Cyan": 10.5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Summoning Battles / Cyan / Battle 14": 10.5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Summoning Battles / Teal": 3.5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Summoning Battles / Teal / Battle 9": 3.5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined)": 2.77,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Godshard Set": 15,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Regalis Achievement (379)": 1,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Sovereign Winz Lantern": 150,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Sovereign Winz Lantern / Artifact 32 Base": 25,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Sovereign Winz Lantern / Artifact 32 Tier": 6,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / Spectre Stars Achievement (373)": 1,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Summoning Winner Bonus 19 / Winner Multi (combined) / W6 Merit Shop (Task)": 10,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / Talent Book Library Base": 25,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / W3 Merit Shop Unlock": 10,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / W3 Merit Shop Unlock / Per Point": 2,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Max Book Lv Cap / W3 Merit Shop Unlock / W3 Merit Points Spent": 5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Base Level / Points Invested": 396,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Family Bonus 68 (Mage) / Family Guy Multi (×) — potential buff / Bonus Levels": 0,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Kattlekruk Set": 5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Maroon Warship (Achievement 291)": 1,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Rift Slug (Companion 1)": 25,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Rift Slug (Companion 1) / Bonus": 25,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Rift Slug (Companion 1) / Owned": 1,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Skull of Major Talent (Grimoire 39)": 30,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Sneaking Completions": 5,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Super Bit 47 Lv Bonus": 12,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Super Bit 47 Lv Bonus / Player Lv": 1783,
    "Coin Multi / ➕ Additive Pool / Chaching! (Talent 22) / Effective Level / Bonus Levels / Universe Talent": 5,
  },
};

export const TOP_COIN_CLASS_PROFILE: Readonly<Record<string, string>> = {
  "Beginner": "base",
  "Journeyman": "t22",
  "Maestro": "t22",
  "Voidwalker": "t22",
  "Warrior": "base",
  "Barbarian": "base",
  "Blood_Berserker": "base",
  "Death_Bringer": "base",
  "Squire": "base",
  "Divine_Knight": "base",
  "Archer": "base",
  "Bowman": "base",
  "Siege_Breaker": "base",
  "Hunter": "base",
  "Beast_Master": "base",
  "Wind_Walker": "base",
  "Mage": "base",
  "Shaman": "base",
  "Bubonic_Conjuror": "base",
  "Arcane_Cultist": "base",
  "Wizard": "base",
  "Elemental_Sorcerer": "base",
  "Royal_Guardian": "base"
};

/** The top Coin Multi reference for a class — base merged with its profile. */
export function topCoinFlatForClass(classKey: string | null | undefined): FlatMap {
  const profile = classKey ? TOP_COIN_CLASS_PROFILE[classKey] : undefined;
  const override = profile ? TOP_COIN_PROFILE_OVERRIDES[profile] : undefined;
  return override ? { ...TOP_COIN_FLAT, ...override } : TOP_COIN_FLAT;
}
