// AUTO-GENERATED by web/scripts/gen-dr-items.ts — do not edit by hand.
// Source: web/lib/it/data/website-data.json
// Regenerate: npx tsx web/scripts/gen-dr-items.ts

export type DrItem = {
  /** Raw key in items{} — matches equipOrder slot values. */
  key: string;
  /** Display name, e.g. "Efaunt Helmet". */
  name: string;
  /** Equipment type bucket (HELMET, SHIRT, ATTIRE, TROPHY, …). */
  type: string;
  /** Which DR-family stat the built-in bonus carries. */
  stat:
    | "%_DROP_RATE"
    | "%_DROP_CHANCE"
    | "%_BONUS_DROP_RATE"
    | "%_DROP_RATE_MULTI";
  /** UQ slot the stat lives in (1 = main, 2 = secondary). */
  uq: 1 | 2;
  /** Base value of the built-in stat. Multipliers (Grid 172,
   *  chip doubling) are applied at runtime in equipment.ts. */
  val: number;
};

export const DR_ITEMS: DrItem[] = [
  { key: "EquipmentGown3", name: "Evergreen Robe", type: "ATTIRE", stat: "%_DROP_RATE", uq: 2, val: 75 },
  { key: "EquipmentGown1", name: "Cobalt Robe", type: "ATTIRE", stat: "%_DROP_RATE", uq: 2, val: 60 },
  { key: "EquipmentBows14", name: "Doublestring Godshooter", type: "BOW", stat: "%_DROP_RATE", uq: 2, val: 20 },
  { key: "CatchingNet12", name: "Wrangler of the Qoxzul", type: "BUG_CATCHING_NET", stat: "%_DROP_RATE", uq: 2, val: 10 },
  { key: "EquipmentCape7", name: "Molten Cloak", type: "CAPE", stat: "%_DROP_RATE", uq: 1, val: 30 },
  { key: "EquipmentCape17", name: "Gilded Emperor Wings", type: "CAPE", stat: "%_DROP_RATE", uq: 2, val: 10 },
  { key: "ObolHyper0", name: "Hyper Obol of Lucky Rolls", type: "CIRCLE_OBOL", stat: "%_DROP_RATE", uq: 1, val: 4 },
  { key: "ObolSilverPop", name: "Silver Obol of Pop Pop", type: "CIRCLE_OBOL", stat: "%_DROP_RATE", uq: 1, val: 3 },
  { key: "ObolBronzePop", name: "Bronze Obol of Pop", type: "CIRCLE_OBOL", stat: "%_DROP_RATE", uq: 1, val: 2 },
  { key: "FishingRod12", name: "Angler of the Iliunne", type: "FISHING_ROD", stat: "%_DROP_RATE", uq: 2, val: 10 },
  { key: "EquipmentPunching11", name: "Mittens of the Gods", type: "FISTICUFF", stat: "%_DROP_RATE", uq: 2, val: 40 },
  { key: "EquipmentToolsHatchet10", name: "Annihilator of the Yggdrasil", type: "HATCHET", stat: "%_DROP_RATE", uq: 2, val: 10 },
  { key: "EquipmentHats119", name: "Emperor Kabuto", type: "HELMET", stat: "%_DROP_RATE", uq: 1, val: 25 },
  { key: "EquipmentHats106", name: "Crown of the Gods", type: "HELMET", stat: "%_DROP_RATE", uq: 1, val: 15 },
  { key: "EquipmentHats83", name: "Skulled Helmet of the Divine", type: "HELMET", stat: "%_DROP_RATE", uq: 2, val: 10 },
  { key: "EquipmentHats52", name: "Efaunt Helmet", type: "HELMET", stat: "%_DROP_RATE", uq: 1, val: 5 },
  { key: "ObolLava", name: "Magma Obol of Big Time Domeo", type: "HEXAGON_OBOL", stat: "%_DROP_RATE", uq: 1, val: 14 },
  { key: "ObolPlatinumLuck", name: "Platinum Obol of Yahtzee Sixes", type: "HEXAGON_OBOL", stat: "%_DROP_RATE", uq: 1, val: 10 },
  { key: "ObolPlatinumPop", name: "Platinum Obol of Poppity Poppy", type: "HEXAGON_OBOL", stat: "%_DROP_RATE", uq: 1, val: 6 },
  { key: "EquipmentKeychain11", name: "Relic Chain", type: "KEYCHAIN", stat: "%_DROP_RATE", uq: 1, val: 0 },
  { key: "EquipmentNametag3", name: "Balling Nametag", type: "NAMETAG", stat: "%_DROP_RATE", uq: 1, val: 40 },
  { key: "EquipmentNametag21", name: "Treasure Nametag", type: "NAMETAG", stat: "%_DROP_RATE", uq: 1, val: 25 },
  { key: "EquipmentNametag19", name: "Aethermoon Nametag", type: "NAMETAG", stat: "%_DROP_RATE", uq: 2, val: 10 },
  { key: "EquipmentNametag32", name: "Sweet Chocolate Nametag", type: "NAMETAG", stat: "%_DROP_RATE", uq: 2, val: 10 },
  { key: "EquipmentNametag22", name: "Tome Apprentice Nametag", type: "NAMETAG", stat: "%_DROP_RATE", uq: 1, val: 5 },
  { key: "EquipmentNametag10", name: "3rd Anniversary IdleOn Nametag", type: "NAMETAG", stat: "%_DROP_RATE", uq: 2, val: 3 },
  { key: "EquipmentPants31", name: "Emperor Zubon", type: "PANTS", stat: "%_DROP_RATE", uq: 1, val: 35 },
  { key: "EquipmentPants30", name: "Tatters of the Gods", type: "PANTS", stat: "%_DROP_RATE", uq: 1, val: 25 },
  { key: "EquipmentPendant17", name: "Chaotic Amarok Pendant", type: "PENDANT", stat: "%_DROP_RATE", uq: 2, val: 5 },
  { key: "EquipmentPendant18", name: "Strung Steamy", type: "PENDANT", stat: "%_DROP_RATE", uq: 1, val: 3 },
  { key: "EquipmentTools15", name: "Destroyer of the Mollo Gomme", type: "PICKAXE", stat: "%_DROP_RATE", uq: 2, val: 10 },
  { key: "EquipmentHats127", name: "Seal Team Skipper Hat", type: "PREMIUM_HELMET", stat: "%_DROP_RATE", uq: 1, val: 100 },
  { key: "EquipmentHats81", name: "Siege Captain Cap", type: "PREMIUM_HELMET", stat: "%_DROP_RATE", uq: 1, val: 10 },
  { key: "EquipmentHats116", name: "Goldberry", type: "PREMIUM_HELMET", stat: "%_DROP_RATE", uq: 1, val: 10 },
  { key: "EquipmentHats90", name: "Straw Hat", type: "PREMIUM_HELMET", stat: "%_DROP_RATE", uq: 1, val: 5 },
  { key: "EquipmentHats46", name: "Strawbiggy", type: "PREMIUM_HELMET", stat: "%_DROP_RATE", uq: 1, val: 4 },
  { key: "EquipmentHats108", name: "3rd Anniversary Ice Cream Topper", type: "PREMIUM_HELMET", stat: "%_DROP_RATE", uq: 2, val: 3 },
  { key: "EquipmentHats34", name: "Parasite", type: "PREMIUM_HELMET", stat: "%_DROP_RATE", uq: 1, val: 3 },
  { key: "EquipmentHats50", name: "Green Beanie", type: "PREMIUM_HELMET", stat: "%_DROP_RATE", uq: 1, val: 3 },
  { key: "EquipmentHats32", name: "Bandit Bob Mask", type: "PREMIUM_HELMET", stat: "%_DROP_RATE", uq: 1, val: 2 },
  { key: "EquipmentHats40", name: "Pardoned Turkey", type: "PREMIUM_HELMET", stat: "%_DROP_RATE", uq: 1, val: 2 },
  { key: "EquipmentHats130", name: "Leprechaun Hat", type: "PREMIUM_HELMET", stat: "%_DROP_RATE", uq: 1, val: 2 },
  { key: "EquipmentHats129", name: "Polkadot Beanie", type: "PREMIUM_HELMET", stat: "%_DROP_RATE", uq: 1, val: 1 },
  { key: "EquipmentHats134", name: "Starry Hairpins", type: "PREMIUM_HELMET", stat: "%_DROP_RATE", uq: 1, val: 1 },
  { key: "EquipmentShirts39", name: "Emperor Sokutai Ho", type: "SHIRT", stat: "%_DROP_RATE", uq: 1, val: 40 },
  { key: "EquipmentShirts38", name: "Robe of the Gods", type: "SHIRT", stat: "%_DROP_RATE", uq: 1, val: 30 },
  { key: "EquipmentShoes40", name: "Emperor Geta", type: "SHOES", stat: "%_DROP_RATE", uq: 1, val: 40 },
  { key: "EquipmentShoes38", name: "Drip of the Gods", type: "SHOES", stat: "%_DROP_RATE", uq: 1, val: 30 },
  { key: "EquipmentShoes36", name: "Devious Slippers of the Divine", type: "SHOES", stat: "%_DROP_RATE", uq: 1, val: 15 },
  { key: "ObolPinkLuck", name: "Dementia Obol of Infinisixes", type: "SPARKLE_OBOL", stat: "%_DROP_RATE", uq: 1, val: 15 },
  { key: "ObolPinkPop", name: "Dementia Obol of Pop Pop Pop Pop", type: "SPARKLE_OBOL", stat: "%_DROP_RATE", uq: 1, val: 9 },
  { key: "EquipmentSword9", name: "Massive Godbreaker", type: "SPEAR", stat: "%_DROP_RATE", uq: 2, val: 20 },
  { key: "ObolHyperB0", name: "Hyper Obol of Rare Drops", type: "SQUARE_OBOL", stat: "%_DROP_RATE", uq: 1, val: 10 },
  { key: "ObolKnight", name: "Vigilant Obol of Ice Guard", type: "SQUARE_OBOL", stat: "%_DROP_RATE", uq: 1, val: 8 },
  { key: "ObolGoldLuck", name: "Golden Obol of Triple Sixes", type: "SQUARE_OBOL", stat: "%_DROP_RATE", uq: 1, val: 7 },
  { key: "ObolSilverLuck", name: "Silver Obol of Double Sixes", type: "SQUARE_OBOL", stat: "%_DROP_RATE", uq: 1, val: 5 },
  { key: "ObolGoldPop", name: "Golden Obol of Poppity Pop", type: "SQUARE_OBOL", stat: "%_DROP_RATE", uq: 1, val: 4 },
  { key: "ObolFrog", name: "Grumpy Obol of the Grandfrogger", type: "SQUARE_OBOL", stat: "%_DROP_RATE", uq: 2, val: 1 },
  { key: "TrapBoxSet10", name: "Containment of the Zrgyios", type: "TRAP_BOX_SET", stat: "%_DROP_RATE", uq: 2, val: 10 },
  { key: "Trophy25", name: "Luckiest Lad", type: "TROPHY", stat: "%_DROP_RATE", uq: 1, val: 777 },
  { key: "Trophy20", name: "Luckier Lad", type: "TROPHY", stat: "%_DROP_RATE", uq: 1, val: 50 },
  { key: "Trophy17", name: "One of the Divine", type: "TROPHY", stat: "%_DROP_RATE", uq: 1, val: 42 },
  { key: "Trophy2", name: "Lucky Lad", type: "TROPHY", stat: "%_DROP_RATE", uq: 1, val: 7 },
  { key: "Trophy9", name: "Ultra Unboxer", type: "TROPHY", stat: "%_DROP_RATE", uq: 1, val: 3 },
  { key: "EquipmentWands13", name: "Magnifique Godcaster", type: "WAND", stat: "%_DROP_RATE", uq: 2, val: 20 },
  { key: "WorshipSkull11", name: "Crystal Skull of Esquire Vnoze", type: "WORSHIP_SKULL", stat: "%_DROP_RATE", uq: 2, val: 10 },
  { key: "EquipmentGown5", name: "Corsair Uniform", type: "ATTIRE", stat: "%_BONUS_DROP_RATE", uq: 1, val: 50 },
  { key: "EquipmentCape18", name: "Chains of the Gilded Vaultguard", type: "CAPE", stat: "%_DROP_RATE_MULTI", uq: 2, val: 40 },
  { key: "EquipmentNametag33", name: "Pot of Gold Nametag", type: "NAMETAG", stat: "%_DROP_RATE_MULTI", uq: 1, val: 30 },
  { key: "EquipmentNametag20", name: "Deadbones Nametag", type: "NAMETAG", stat: "%_DROP_RATE_MULTI", uq: 1, val: 25 },
  { key: "EquipmentNametag28", name: "Tome Legend Nametag", type: "NAMETAG", stat: "%_DROP_RATE_MULTI", uq: 1, val: 20 },
  { key: "EquipmentNametag29", name: "Reliquarium Nametag", type: "NAMETAG", stat: "%_DROP_RATE_MULTI", uq: 1, val: 20 },
  { key: "EquipmentNametag35", name: "5th Anniversary IdleOn Nametag", type: "NAMETAG", stat: "%_DROP_RATE_MULTI", uq: 1, val: 5 },
  { key: "EquipmentHats102", name: "Fanned Blossomage", type: "PREMIUM_HELMET", stat: "%_DROP_RATE_MULTI", uq: 1, val: 2 },
  { key: "EquipmentHats86", name: "Carrotman Mask", type: "PREMIUM_HELMET", stat: "%_DROP_RATE_MULTI", uq: 1, val: 1 },
  { key: "EquipmentHats96", name: "Bamboo Hat", type: "PREMIUM_HELMET", stat: "%_DROP_RATE_MULTI", uq: 1, val: 1 },
  { key: "Trophy24", name: "Nine Dart Finish", type: "TROPHY", stat: "%_DROP_RATE_MULTI", uq: 1, val: 9 },
];
